### ISSUE TITLE
Failed to compile with zksolc, LLVM IR generator definition pass error

### ISSUE THREAD

**Issue by Senya123** [matter-labs/hardhat-zksync#1040]
Could someone help me to resolve the issue. I install the zkSync foundry compiler and right now i can't run any Test!!!!!!!!
<img width="1557" alt="Screenshot 2024-05-03 at 15 09 43" src="https://github.com/matter-labs/hardhat-zksync/assets/26926656/6900c430-d48e-4268-b780-50163ac90d65">

**Comment by dutterbutter** [comment]
@Senya123 can you please post this to the `foundry-zksync` [repo](https://github.com/matter-labs/foundry-zksync) rather than here. As this repo is for hardhat plugins. 

Please also provide more details in the issue so we can help debug. Like steps to reproduce and a link to the repo. 

Thanks.
