### ISSUE TITLE
`deploy-zksync:libraries` doesn't work for external libraries that are in a project sub package

### ISSUE THREAD

**Issue by gte620v** [matter-labs/hardhat-zksync#1048]
#### 💥 Plugin name

`deploy-zksync:libraries`

#### 📝 Description

`yarn hardhat deploy-zksync:libraries --network zkTestnet` throws an error if the external library is in a subpackage.

e.g.

If I have a contract that imports an external library such as

```solidity
pragma solidity ^0.8.25;
// import {Deployer} from "./Deployer.sol"; // works
import {Deployer} from "@project/lib/contracts/Deployer.sol";  // does not work
contract Example {
    function deploy(
    ) external view returns (uint256) {
        return Deployer.deploy();
    }
}
```

where the library is

```solidity
pragma solidity ^0.8.25;
library Deployer {
    function deploy(
    ) external pure returns (uint256) {
        return 10;
    }
}
```

I get success when the external lib is in the same project.
```
Compiling contracts for zkSync Era with zksolc v1.4.1 and solc v0.8.25
Compiling 1 Solidity file

Generating typings for: 1 artifacts in dir: typechain for target: ethers-v6
Successfully generated 6 typings!
Successfully compiled 1 Solidity file
Deploying contracts/Example.sol:Example .....
Deployed contracts/Example.sol:Example at 0x...
All libraries deployed successfully!
Please run yarn hardhat compile to compile all contracts
```

But when I use `import {Deployer} from "@project/lib/contracts/Deployer.sol";` the command fails:

```
Error HH404: File @project/lib/contracts/Deployer.sol, imported from contracts/Example.sol, not found.
```

This process works fine for the normal hardhat compiler for other EVM networks.  That is, the `solc` compiler has no problem finding the subpackage and compiling the contract.

#### 🔄 Reproduction Steps

See Description

#### 🤔 Expected Behavior

Expect external libs in sub packages to just work.

#### 😯 Current Behavior

They don't

**Comment by dutterbutter** [comment]
@nikola-bozin-txfusion could you review issue this when possible please 😃

**Comment by nikola-bozin-txfusion** [comment]
Hey @gte620v,
I suggest you to use [this](https://www.npmjs.com/package/hardhat-dependency-compiler) package to explicitly mark a import from node_modules, like this:
```
    dependencyCompiler: {
        paths: [
          '@project/lib/contracts/Deployer.sol',
        ],
      },
```
also dont forget to import:

`import 'hardhat-dependency-compiler'`
at the top of hardhat.config file. 

Now you should be able to use it like this:
`import {Deployer} from "@project/lib/contracts/Deployer.sol";` in your Solidity file.

If you are using remapping, please make sure that imports are correctly mapped in your preprocessor function. Also make sure that you imported `hardhat-preprocessor` in your `hardhat.config` file.

**Comment by gte620v** [comment]
Great; that works. thanks!
