### ISSUE TITLE
Vyper-example does not work

### ISSUE THREAD

**Issue by ngmisl** [matter-labs/hardhat-zksync#1202]
Error HH700: Artifact for contract ".__VYPER_MINIMAL_PROXY_CONTRACT:__VYPER_MINIMAL_PROXY_CONTRACT" not found

**Comment by kiriyaga-txfusion** [comment]
Hello @ngmisl , could you provide details on how this error occurred? Our [action](https://github.com/matter-labs/hardhat-zksync/actions/runs/9695969612/job/26756871260) (Find Test zkvyper example) shows that the tests ran successfully for the vyper-example.

**Comment by hedgar2017** [comment]
@kiriyaga-txfusion I believe I've found the problem.
Will release the fix soon.

**Comment by hedgar2017** [comment]
Fixed in zkvyper v1.5.2!
