### ISSUE TITLE
I use the vypey Greeter tutorial to deploy the contract, there is an error:'cannot estimate gas; transaction may fail or may require manual gas limit' 

### ISSUE THREAD

**Issue by liny52** [matter-labs/hardhat-zksync#134]
I use the vypey Greeter tutorial to deploy the contract, there is an error:'cannot estimate gas; transaction may fail or may require manual gas limit' 

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/40197424/198833642-f63970d7-0183-4bf0-bd57-5dd1639b5e7a.png">

package.json
{
  "name": "harhat-zksync-example-vyper",
  "version": "0.1.0",
  "author": "Matter Labs",
  "license": "MIT",
  "scripts": {
    "lint": "yarn prettier --check && yarn eslint",
    "lint:fix": "yarn eslint --fix",
    "fmt": "yarn prettier --write",
    "eslint": "eslint deploy/*.ts",
    "prettier": "prettier deploy/*.ts",
    "test": "mocha test/tests.ts --exit",
    "build": "tsc --build .",
    "clean": "rimraf dist"
  },
  "devDependencies": {
    "@matterlabs/hardhat-zksync-deploy": "^0.5.2",
    "@matterlabs/hardhat-zksync-vyper": "^0.1.5",
    "@types/node": "^17.0.21",
    "@typescript-eslint/eslint-plugin": "4.29.2",
    "@typescript-eslint/parser": "5.13.0",
    "eslint": "^8.10.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-prettier": "3.4.0",
    "prettier": "2.3.2",
    "rimraf": "^3.0.2",
    "ts-node": "^10.6.0"
  },
  "dependencies": {
    "@matterlabs/hardhat-zksync-solc": "^0.3.10",
    "@nomiclabs/hardhat-vyper": "^3.0.1",
    "ethers": "~5.7.0",
    "hardhat": "^2.12.1",
    "typescript": "^4.8.4",
    "zksync-web3": "^0.9.0"
  },
  "prettier": {
    "tabWidth": 4,
    "printWidth": 120,
    "parser": "typescript",
    "singleQuote": true,
    "bracketSpacing": true
  }
}

hardhat.config.ts
`import "@nomiclabs/hardhat-vyper";
 import "@matterlabs/hardhat-zksync-vyper";
 import "@matterlabs/hardhat-zksync-deploy";
 import { HardhatUserConfig } from 'hardhat/config';
const config: HardhatUserConfig = {
  zkvyper: {
    version: "1.2.0",
    compilerSource: "binary",
    // compilerSource: "docker",
    // settings: {
    //   experimental: {
    //     dockerImage: "matterlabs/zkvyper",
    //     tag: "latest"
    //   }
    // },
  },
  zkSyncDeploy: {
    zkSyncNetwork: "https://zksync2-testnet.zksync.dev",
    ethNetwork: "goerli",
  },
  networks: {
    hardhat: {
      zksync: true,
    },
  },
  // Currently, only Vyper ^0.3.3 is supported.
  vyper: {
    version: "0.3.3"
  },
};
export default config;
`

**Comment by ly0va** [comment]
It seems that you are using an obsolete version of our `zksync-web3` SDK. The latest version is `0.11.1`

Please update and try again.

**Comment by liny52** [comment]
Thanks a lot, I tried to upgrade zksync-web to 0.11.1 and it worked, thanks
