### ISSUE TITLE
message: 'Transaction requires too much gas or exceed VM execution limits to commit on L1'

### ISSUE THREAD

**Issue by richiezk** [matter-labs/hardhat-zksync#138]
reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","error":{"code":3,"message":"Failed to submit transaction: Transaction requires too much gas or exceed VM execution limits to commit on L1","data":{"code":104,"message":"Transaction requires too much gas or exceed VM execution limits to commit on L1"}},"id":54}\n',

How to solve this problem? code must be split？

**Comment by ly0va** [comment]
Hi @richiezk 

If you encounter this error during deployment, it means that the amount of gas needed to deploy is greater than allowed for a single transaction.

Try splitting and deploying separately.
In future, the limit might increase.

**Comment by richiezk** [comment]
> Hi @richiezk
> 
> If you encounter this error during deployment, it means that the amount of gas needed to deploy is greater than allowed for a single transaction.
> 
> Try splitting and deploying separately. In future, the limit might increase.

Thank you very much for your answer, I try to split the code

**Comment by ly0va** [comment]
@richiezk the limit on testnet was increased, this should have helped your issue.
Feel free to reopen if you're still having trouble.
