### ISSUE TITLE
Error in plugin @matterlabs/hardhat-zksync-solc: Failed to download

### ISSUE THREAD

**Issue by lalawila** [matter-labs/hardhat-zksync#148]
Error in plugin @matterlabs/hardhat-zksync-solc: Failed to download https://github.com/matter-labs/zksolc-bin/raw/main/win32-amd64/zksolc-win32-amd64-v1.2.0 - 404 received.

![image](https://user-images.githubusercontent.com/26580242/203865220-a6115b6b-c378-460e-8d6e-4ae05f58138c.png)

There is no file in the url. Maybe the url should be `https://github.com/matter-labs/zksolc-bin/raw/main/windows-amd64/zksolc-windows-amd64-gnu-v1.2.0.exe` ?

![image](https://user-images.githubusercontent.com/26580242/203865814-940f431b-b6da-4cda-87b9-acaf474106a7.png)

**Comment by ly0va** [comment]
Thanks for the report @lalawila, you are correct, the URL is malformed.

Will fix

**Comment by EasyChris** [comment]
when i try many times rum `npx hardhat compile` command this problems is solve

**Comment by FireDragonZL** [comment]
I ran into the same problem, which could be handled by downloading the binaries and introducing them through a configuration file `hardhat.config.js` , for example:
```javascript
import "@matterlabs/hardhat-zksync-solc";

module.exports = {
  zksolc: {
    version: "1.3.1",
    compilerSource: "binary",
    settings: {
        compilerPath: "/[your file path]/zksolc-linux-amd64-musl-v1.3.1",  // ignored for compilerSource: "docker"
        libraries:{}, // optional. References to non-inlinable libraries
        isSystem: false, // optional.  Enables Yul instructions available only for zkSync system contracts and libraries
        forceEvmla: false // optional. Falls back to EVM legacy assembly if there is a bug with Yul
    },
  },
  ......
}
```
