### ISSUE TITLE
Create2 deployment type should make use of `Create2Factory` 

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/hardhat-zksync#1543]
#### 💥 Plugin name

`hardhat-zksync-deploy`

#### 📝 Description

Deploying the same create2 contract with different deployer wallets should result in the same deterministic address. For example, deploying to zksync-testnet and abstract-testnet **with two different accounts** should still result in the same address.

**zksync-testnet**
```
bunx hardhat deploy-zksync:contract --deployment-type create2 --salt 0x7935910912126667836566922594852029127629416664760357073852948630 --network zksync-testnet --contract-name Counter
```

**abstract-testnet**
```
bunx hardhat deploy-zksync:contract --deployment-type create2 --salt 0x7935910912126667836566922594852029127629416664760357073852948630 --network abstract-testnet --contract-name Counter
```

Using different deployer wallets here will result in two distinct create2 addresses. We should make use of `Create2Factory` so the deployer wallet is not accounted for. Example script below can be used to determine create2 address regardless of deployer wallet.

```
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { utils } from "zksync-ethers";
import { hexlify } from "ethers";

const deployScript = async function (hre: HardhatRuntimeEnvironment) {
  console.info(`Running deploy script for the Counter contract`);

  const artifact = await hre.deployer.loadArtifact("Counter");
  const counterBytecodeHash = hexlify(utils.hashBytecode(artifact.bytecode));
  const salt =
    "0x7935910912126667836566922594852029127629416664760357073852948630";
  const create2FactoryAddress = "0x0000000000000000000000000000000000010000";

  const deterministicAddress = utils.create2Address(
    create2FactoryAddress,
    counterBytecodeHash,
    salt,
    "0x"
  );
  console.log("Counter contract address: ", deterministicAddress);
};

export default deployScript;
```

Rather then having to use the above script, it would be nice to make use of the above mentioned command.
 
It seems it takes account the deployer address 

#### 🔄 Reproduction Steps

1. Deploy `Counter` contract using create2 with "wallet A" on zksync-testnet observe the address 
2. Deploy the same contract using create2 with "wallet B" on abstract-testnet observe the address 

#### 🤔 Expected Behavior

Deterministic address regardless of deployer wallet

#### 😯 Current Behavior

Different address due to different deployer wallets being used

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by kiriyaga-txfusion** [comment]
Change for create2 and create2Account from ContractDeployer to Contract2Factory is merged and released with a new version of the zksync-ethers 1.15.1.
