### ISSUE TITLE
Test failures with new version of the era test node

### ISSUE THREAD

**Issue by kiriyaga-txfusion** [matter-labs/hardhat-zksync#1550]
#### 💥 Plugin name

hardhat-zksync-ethers

#### 📝 Description

With the new version of the zkSync Era Test Node, the fee estimation is calculated dynamically, which is causing the tests of the plugin to fail.

#### 🔄 Reproduction Steps

1. Navigate to hardhat-zksync-ethers plguins package.
2. Run pnpm test

#### 🤔 Expected Behavior

All tests should pass successfully.

#### 😯 Current Behavior

Some of the tests are failing

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by lafinion** [comment]
Hey folks, 

 I have nearly the same issue. 
 
 looks like the latest commit broke the gas estimation logic. 
 
 So tests are failing, moreover sometimes it fails less, sometimes more. It is completely unstable (the same contract, the same test - no changes and it was successfull)

**Comment by lafinion** [comment]
As a temporary solution, you can run the node with this tag (previous version)

npx hardhat node-zksync --tag 0.1.0-alpha.32

Hope, that would help.

**Comment by kiriyaga-txfusion** [comment]
Fixed and merged to the main branch.
