### ISSUE TITLE
how to implement multiple compilation targets with hardhat?

### ISSUE THREAD

**Issue by mikhailxyz** [matter-labs/hardhat-zksync#188]
At Safe, we're trying to implement zksync support but we want to keep our contracts compiled for EVM with `solc@0.7.6`

I implemented conditional compiler settings depending on an environment variable:
```js
const getCompilerSettings = (): CompilerSettings => {
  if (TARGET_ZKSYNC) {
    return {
      solidity: {
        version: "0.8.15",
      },
      zksolc: {
        version: "1.1.0",
        compilerSource: "binary",
        settings: {},
      },
    };
  }

  return {
    solidity: {
      compilers: [
        { version: primarySolidityVersion, settings: soliditySettings },
        { version: "0.6.12" },
        { version: "0.5.17" },
      ],
    },
  };
};
```

The full source can be found here:
https://github.com/safe-global/safe-contracts/blob/zksync/hardhat.config.ts

The issue I'm facing is when `TARGET_ZKSYNC` is not set, it still invokes the zksolc compiler and does not generate solidity files

```
~/projects/safe/safe-contracts/build zksync ❯ tree -L 1                                                                                                                                                   
.
├── artifacts-zk
└── cache-zk
```

**Comment by uF4No** [comment]
I think this can be caused by using `zksync: true` on the hardhat network, which is the default. Can you try also conditionally changing this to `false` when `TARGET_ZKSYNC` is not set?

**Comment by mikhailxyz** [comment]
@uF4No have just tested this and it worked 🎉 thank you!
