### ISSUE TITLE
1.3.2 zksolc not compatible with 0.8.18 Solidity

### ISSUE THREAD

**Issue by stevyhacker** [matter-labs/hardhat-zksync#209]
I've been trying to get the zksync compiler to compile contracts which use 0.8.18 but I consistently get this error:
```
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
error Command failed with exit code 1.
```

I tried multiple versions but it happens even with all the latest  zksync tools and 1.3.2 zksolc compiler binary.

**Comment by mpopovac-txfusion** [comment]
Support for Solidity 0.8.18 is fixed with 1.3.5 release of the zksync compiler.

**Comment by zouguangxian** [comment]
How do you think I could fix it? I encountered this issue when building contracts with zksolc-1.3.16 and solc-0.8.17.

**Comment by vasinl124** [comment]
@mpopovac-txfusion 

Hi, maybe you can help me with this. I just have a MBP on Sonoma. 

I follow the instructions from this link - [https://docs.zksync.io/build/quick-start/hello-world.html#prerequisites](https://docs.zksync.io/build/quick-start/hello-world.html#prerequisites) I can compile the contract with solc but with zksolc I always get this error. I tried this same code on my PC. it works as expected just only this laptop that doesn't work :( 

I tried using different node version, different zksolc/solc version but still got the same error.

Please advise

![image](https://github.com/matter-labs/hardhat-zksync/assets/6901435/7c0f2151-7d8a-43aa-8323-9168e63f2673)

**Comment by janjakubnanista** [comment]
Just add an explicit `solc` dependency to your `package.json` @zouguangxian - the underlying error comes from `require(undefined)`

**Comment by 0xsiddharthks** [comment]
@janjakubnanista Thanks! adding solc to the dependencies worked.

**Comment by shankars99** [comment]
@0xsiddharthks Thanks! adding stuff into the compilers worked.

adding `eraVersion: '1.0.0'` into `config:solidity:compilers` under hardhat config solves this:

```
solidity: {
        compilers: [
            {
                version: '0.8.22',
                eraVersion: '1.0.0', //optional. Compile contracts with EraVM compiler
                settings: {
                    optimizer: {
                        enabled: true,
                        runs: 200,
                    },
                },
            },
        ],
    },
    zksolc: {
        version: '1.4.1', // Version of the zksolc compiler to use
        compilerSource: 'binary', // or 'docker' if you prefer
        settings: {
            optimizer: {
                enabled: true,
                mode: 'z',
            },
            libraries: {},
        },
    },
```
