### ISSUE TITLE
ZkSyncVerifyPluginError: Contract verification is still pending

### ISSUE THREAD

**Issue by merlincdj** [matter-labs/hardhat-zksync#217]
I deploy the contract on the latest testnet, get this error when I try to verify by using `yarn hardhat verify --network zkSyncTestnet 0x28881F414c3F79C94Fb8EDd39A416af40A90184e "0x0faF6df7054946141266420b43783387A78d82A9"`, may I ask how to fix it?

**Comment by FilipTxFusion** [comment]
In the latest version of the verify plugin you are able to see your verification ID for each verify request. Using it, you can run a new command that will check the status of your, previously submitted, verification request.

You can find more info about this process in the verify documentation page: https://era.zksync.io/docs/api/hardhat/hardhat-zksync-verify.html#verification-status-check

**Comment by merlincdj** [comment]
Okay, update to the latest version of `@matterlabs/hardhat-zksync-verify` and `@nomiclabs/hardhat-etherscan` is able to verify now, thanks!
