### ISSUE TITLE
hardhat zksync-solc breaks when using compiler overrides

### ISSUE THREAD

**Issue by mikemcdonald** [matter-labs/hardhat-zksync#236]
When using solidity compiler overrides for specific contracts in the hardhat config, hardhat zksync-solc only loops through the compilers config to `filterSupportedOutputSelections` on compiler.settings.outputSelection.

https://github.com/matter-labs/hardhat-zksync/blob/b40f19bda82392302da3dc2612649a75404e807c/packages/hardhat-zksync-solc/src/index.ts#L59

This also needs to be applied on each override `hre.config.solidity.overrides`, otherwise zksolc will throw with something like `unknown variant `evm.bytecode`

**Comment by mpopovac-txfusion** [comment]
Thanks for the feedback. This will be fixed in the next release.

**Comment by mikemcdonald** [comment]
Looks like this is fixed so closing, thanks!
