### ISSUE TITLE
How to Deploy an Upgradeable Smart Contract using hardhat-zksync-deploy

### ISSUE THREAD

**Issue by thangnn91** [matter-labs/hardhat-zksync#237]
I can easily deploy an upgradeable SC with hardhat in other EVM platform with code
```bash
  import { upgrades } from "hardhat";

  const Proxy = await ethers.getContractFactory("Proxy");
  const proxy= await upgrades.deployProxy(
    Proxy,
    [
      params,
    ],
    {
      initializer: "initialize",
    }
  );
```
How can I do the same on zksync, could anyone give me an example about upgradeable SC or Is there a method on @matterlabs/hardhat-zksync-deploy that does it?
Such as:
```bash
  import {Deployer} from '@matterlabs/hardhat-zksync-deploy';

  const Proxy= await deployer.loadArtifact('Proxy');
  const proxy = await deployer.deployProxy(Proxy, [params]);
```

**Comment by makinghappen** [comment]
see https://github.com/devopsdao/devopsdao-smart-contract-diamond which uses EIP-2535 Diamonds upgradable smart contracts.

**Comment by beatercode** [comment]
@makinghappen thank you

**Comment by FilipTxFusion** [comment]
We still don't have the official version of the hardhat plugin package that supports upgradable smart contracts. We will add it in the future so you can easily deploy and upgrade contracts on zkSync.

**Comment by FilipTxFusion** [comment]
Closing this thread, since the we released the official hardhat-zksync-upgradable plugin.

Code: https://github.com/matter-labs/hardhat-zksync/tree/main/packages/hardhat-zksync-upgradable
Documentation: https://era.zksync.io/docs/tools/hardhat/hardhat-zksync-upgradable.html
