### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by madtechnologistproton** [matter-labs/hardhat-zksync#240]
I got the error : "TypeError: Cannot convert undefined or null to object" when try to deploy smart contract using hardhat 
Detail:
![image](https://user-images.githubusercontent.com/121210553/229473683-9d937524-4dcf-4ac4-9c49-122537a9b09b.png)

Please support me to fix that error
Thank team

**Comment by mpopovac-txfusion** [comment]
Hi @madtechnologistproton , after reviewing the provided log, it appears that you are utilizing the @openzeppelin/hardhat-upgrades plugin for deploying smart contracts with proxy support. However, please note that this functionality is currently incompatible with zksync. Rest assured, our team is actively working on a plugin that will enable proxy functionality specifically for zksync. Although it is still under development, you may consider using it for testing purposes. Here is the link to the [hardhat-zksync-upgradable](https://www.npmjs.com/package/@matterlabs/hardhat-zksync-upgradable) package.
