### ISSUE TITLE
A space in the path to the compiler causes a crash

### ISSUE THREAD

**Issue by vladyan18** [matter-labs/hardhat-zksync#256]
At least on Windows a space in the path to the compiler (default c://users/\<user\>/AppData/...) causes compilation to crash without explanation. Most likely, you forgot to wrap the path in quotes somewhere.

**Comment by FilipTxFusion** [comment]
Hi @vladyan18, can you please provide us with more data on when you get the error so we can try to reproduce it?

**Comment by vladyan18** [comment]
@FilipTxFusion Try placing the compiler binaries in a directory with spaces in the path and redefine the path in the hardhat/plugin.

Or try to compile the contract by creating a user in Windows with a space in the name.

**Comment by vladyan18** [comment]
Since I created this issue, it seems that several versions have passed, the problem may not appear anymore, but it's worth checking.
