### ISSUE TITLE
zk-solc compilation does not work in hre.

### ISSUE THREAD

**Issue by dewindtk** [matter-labs/hardhat-zksync#269]
When i run `npx hardhat compile`, I do not think it successfully compiles using the zksolc but the regular solc. 
my artifacts folder is named 'artifacts' and not 'artifacts-zk'. How do I set it up so it uses the zksolc?

**Comment by mpavlovic-txfusion** [comment]
This shouldn't be the case if you imported the `hardhat-zksync-solc` plugin in your `hardhat.config` and configured it correctly (https://era.zksync.io/docs/api/hardhat/hardhat-zksync-solc.html). Can you paste here the `hardhat.config` that you are using?

**Comment by mpavlovic-txfusion** [comment]
You need to choose whether you want to use CommonJS module system (default for js files) or ES modules.
For CommonJS, just remove the `"type": "module"` from package.json and use` require("hardhat-zksync-solc");` for importing and `module.exports` for exporting.
For ES modules, use `"type": "module"` in package.json (or `.mjs` file extension) and use `import "hardhat-zksync-solc"` and `export default`.
Here is the article explaining the differences of these 2 module systems https://www.knowledgehut.com/blog/web-development/commonjs-vs-es-modules

**Comment by NitinSadekar17** [comment]
Deprecated zksolc compiler version in hardhat config file (1.3.6). Please use versions 1.3.13 to 1.3.14.
showing this problem when i deploy contact on zksync era mainnet
