### ISSUE TITLE
I can't verify the zkSync Era contract.

### ISSUE THREAD

**Issue by zkLaunch-dev** [matter-labs/hardhat-zksync#286]
I am using: yarn hardhat verify --network zkSyncMainnet [contract address]

However, I am getting an error:

Error: Axios error (code: ERR_BAD_REQUEST) during the contract verification request. Reason: There is no deployed contract on this address.

**Comment by michecode** [comment]
bump. getting the same issue here with version 0.1.7

**Comment by FilipTxFusion** [comment]
Hi @zkLaunch-dev @michecode , we released a new version of the plugin - 0.1.8. Please try to use that one and see if the error persists.
If you still can not verify your contract, please provide as much context as possible about your project (contract address, hardhat config, contract code, ...) so we can try to help you solve the issue.

**Comment by sobolev-igor** [comment]
Hey everyone! I'm still having this issue with [hardhat-zksync](https://github.com/matter-labs/hardhat-zksync) 1.2.0
Unfortunately, the repo is private but I can provide an access if required.

**Comment by kiriyaga-txfusion** [comment]
Hello, thanks for the reporting can you give us some access so we can try.

**Comment by sobolev-igor** [comment]
Ah, @kiriyaga-txfusion, never mind, I forgot to add `verifyURL` to the network config 😅
