### ISSUE TITLE
Error in plugin @matterlabs/hardhat-zksync-solc: Connect Timeout Error

### ISSUE THREAD

**Issue by sprprashanth1443** [matter-labs/hardhat-zksync#288]
Hi Team, While i compile the solidity contract using 'hardhat' I am getting below error with default hardhat config given https://era.zksync.io/docs/dev/building-on-zksync/hello-world.html#initialize-the-project

Using node version v18+

[
<img width="1178" alt="Screenshot 2023-05-21 at 1 01 31 PM" src="https://github.com/matter-labs/hardhat-zksync/assets/64004106/4e6a9efe-e27d-4e43-a799-b3b1920a51a4">
](url)

**Comment by Sandeep-Narahari** [comment]
Could anyone please look into this 

Thank you

**Comment by mpopovac-txfusion** [comment]
Hi @sprprashanth1443, do you still have the same issue?

**Comment by srslafazan** [comment]
We've reproduced this on an OSX m1 OS as well @mpopovac-txfusion 

@AjmalAhamedKodakkat

**Comment by AjmalAhamedKodakkat** [comment]
```
Downloading zksolc 1.3.10
Error in plugin @matterlabs/hardhat-zksync-solc: Connect Timeout Error

For more info run Hardhat with --show-stack-traces
```

**Comment by mpopovac-txfusion** [comment]
We released the new version of `@matterlabs/hardhat-zksync-solc` hardhat plugin (0.4.0) with increased timeout. Sometimes when the internet's not up to speed, this problem surfaces. Don't hesitate to reach out if it persists.
