### ISSUE TITLE
hardhat-zksync-deploy doesn't log deployed address nor save deployment result

### ISSUE THREAD

**Issue by levx-me** [matter-labs/hardhat-zksync#294]
'hardhat-deploy' logs deployed address and saved relevant data under /deployments

'hardhat-zksync-deploy' doesn't

why?

**Comment by mpopovac-txfusion** [comment]
Currently, `hardhat-zksync-deploy` doesn't have a support deployment cache feature. However, you have the option to use the `hardhat-deploy` community plugin for deploying contracts on zkSync as well.

**Comment by levx-dev** [comment]
can I use `hardhat-deploy` as well? 
then what's the role of `hardhat-zksync-deploy'?

**Comment by anhlh-edsolabs** [comment]
> can I use `hardhat-deploy` as well? then what's the role of `hardhat-zksync-deploy`?

Hi @levx-dev, 
Recently I've been developing this helper plugin for deploying contract on zksync, and continuosly adding features to it. At the moment you can run it with the hardhat `deploy` task, then the deployment data including Proxy, implementation address, initialization arguments, and so on, are logged into a json file in `deployments-zk` folder.

Here's the repo, feel free to fork and contribute to the development: [zksync-deploy-helper](https://github.com/anhlh-edsolabs/zksync-deploy-helper)
