### ISSUE TITLE
hardhat-zksync-verify: Unknown zksolc version: v1.3.11

### ISSUE THREAD

**Issue by saitama2009** [matter-labs/hardhat-zksync#300]
When I verify contracts on testnet with command

> npx hardhat verify --network testnet xxxx

hardhat-zksync-verify(0.1.7) reports "Unknown zksolc version: v1.3.11"

why？

**Comment by FilipTxFusion** [comment]
Hi @saitama2009, this should be fixed now. Please let us know if you can verify your contract with the newest verify plugin version - 0.1.8

**Comment by friday-james** [comment]
got a similar error: 
`Error in plugin @matterlabs/hardhat-zksync-verify: Unknown zksolc version: v1.3.13` on hardhat-zksync-verify 0.2.0

**Comment by FilipTxFusion** [comment]
@friday-james this should be fixed now.

**Comment by luisvid** [comment]
> @friday-james this should be fixed now.

Hi all!
following the Greeter Example from the tutorials page I got a similar error:
`Error in plugin @matterlabs/hardhat-zksync-verify: Unknown zksolc version: v1.3.17`

I scaffolded a new project by running the command:
`npx zksync-cli create greeter-example --template hardhat_solidity`

These are my dependencies:

```
  "devDependencies": {
    "@matterlabs/hardhat-zksync-deploy": "^0.6.5",
    "@matterlabs/hardhat-zksync-node": "^0.0.1-beta.6",
    "@matterlabs/hardhat-zksync-solc": "^0.4.2",
    "@matterlabs/hardhat-zksync-verify": "^0.2.1",
    "@matterlabs/zksync-contracts": "^0.6.1",
    "@nomiclabs/hardhat-etherscan": "^3.1.7",
    "@openzeppelin/contracts": "^4.6.0",
    "@types/chai": "^4.3.4",
    "@types/mocha": "^10.0.1",
    "chai": "^4.3.7",
    "dotenv": "^16.0.3",
    "ethers": "^5.7.2",
    "hardhat": "^2.12.4",
    "mocha": "^10.2.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4",
    "zksync-web3": "^0.14.3"
  }
```

Thanks!

**Comment by MarkusIvan** [comment]
I have the same

**Comment by devinone** [comment]
Still have the same issue with Win11

**Comment by kiriyaga-txfusion** [comment]
Sometimes new version of zksolc is not registered on the verify backend and this error pops up. Wait a few days for the compiler to be registered or use an older version of the compiler.
