### ISSUE TITLE
specify library address during runtime instead of compile time?

### ISSUE THREAD

**Issue by GopherJ** [matter-labs/hardhat-zksync#302]
currently developers need to prepare each library in advance and put inside hardhat.config.ts like: https://github.com/para-space/paraspace-core/blob/47537c1b5890db5c97e910cae1dfa01272d99a31/hardhat.config.ts#L58-L97

this is not convinient at all and after putting the libraries we still need to compile again which is super slow, is there a way to do a library address replacement during runtime?

**Comment by GopherJ** [comment]
Also if the dependency tree is complex not flat, how should we do it? do we need to deploy from bottom to top and compile again and again?

**Comment by kiriyaga-txfusion** [comment]
Hello @GopherJ, you can check this:
https://era.zksync.io/docs/tools/hardhat/hardhat-zksync-deploy.html#compilation-and-deployment-support-for-missing-libraries
It shows how to use a plugin to detect and deploy missing libraries automatically.
