### ISSUE TITLE
vyper already supports 0.3.9, but hardhat-vyper can't it be compile and downloaded 0.3.9

### ISSUE THREAD

**Issue by liny52** [matter-labs/hardhat-zksync#331]
vyper already supports 0.3.9, but hardhat-vyper can't it be compile and downloaded 0.3.9

<img width="595" alt="image" src="https://github.com/matter-labs/hardhat-zksync/assets/40197424/a1479bd1-55e9-44a8-94bd-541f17c4be25">

package:
{ "name": "zksync-hardhat-template", "version": "1.0.0", "main": "index.js", "author": "Antonio <aug@matterlabs.dev>", "license": "MIT", "devDependencies": { "@matterlabs/hardhat-zksync-deploy": "^0.6.3", "@matterlabs/hardhat-zksync-solc": "^0.4.0", "@matterlabs/hardhat-zksync-verify": "^0.1.8", "@matterlabs/hardhat-zksync-vyper": "^0.2.0", "@nomiclabs/hardhat-etherscan": "^3.1.7", "@nomiclabs/hardhat-vyper": "^3.0.3", "@types/chai": "^4.3.4", "@types/mocha": "^10.0.1", "chai": "^4.3.7", "dotenv": "^16.0.3", "ethers": "^5.7.2", "hardhat": "^2.12.4", "mocha": "^10.2.0", "ts-node": "^10.9.1", "typescript": "^4.9.4", "zksync-web3": "^0.14.3" }, "scripts": { "test": "NODE_ENV=test hardhat test --network zkSyncTestnet", "deploy": "yarn hardhat deploy-zksync --script deploy-greeter.ts", "greet": "yarn hardhat deploy-zksync --script use-greeter.ts" } }

hardhat.config.ts:
`import { HardhatUserConfig } from "hardhat/config";

import "@nomiclabs/hardhat-vyper";
import "@matterlabs/hardhat-zksync-vyper";
import "@matterlabs/hardhat-zksync-deploy";

const config: HardhatUserConfig = {
zkvyper: {
version: "latest", // Uses latest available in https://github.com/matter-labs/zkvyper-bin/
settings: {
// compilerPath: "zkvyper", // optional field with the path to the zkvyper binary.
libraries: {}, // optional. References to non-inlinable libraries
},
},
defaultNetwork: "zkSyncTestnet",
networks: {
hardhat: {
zksync: true, // enables zksync in hardhat local network
},
zkSyncTestnet: {
url: "https://testnet.era.zksync.dev/",
ethNetwork: "goerli",
zksync: true,
},
},
// Currently only Vyper v0.3.3 and v0.3.9 versions are supported.
vyper: {
// version: "0.3.3",
compilers: [
{
version: "0.3.3",
},
{
version: "0.3.9",
},
],
},
};

export default config;

**Comment by mpopovac-txfusion** [comment]
Hey @liny52, this error is raised from the newest version of the Hardhat Vyper plugin (@nomiclabs/hardhat-vyper@3.0.3), which our Hardhat plugin for Vyper (@matterlabs/hardhat-zksync-vyper) relies on.
Currently, it appears that the specific Vyper version you're using isn't supported by this plugin. (you can find list of supported vyper versions [here](https://vyper-releases-mirror.hardhat.org/list.json)). At the moment, the best course of action would be to either wait for the plugin to extend its support to the required versions, or even better you can open an issue on their GitHub repository.

**Comment by liny52** [comment]
> 嘿@liny52，此错误是由最新版本的 Hardhat Vyper 插件 (@nomiclabs/hardhat-vyper@3.0.3) 引发的，我们的 Vyper 的 Hardhat 插件 (@matterlabs/hardhat-zksync-vyper) 依赖于该插件。 目前，该插件似乎不支持您正在使用的特定 Vyper 版本。[（您可以在此处](https://vyper-releases-mirror.hardhat.org/list.json)找到受支持的 vyper 版本列表）。目前，最好的做法是等待插件将其支持扩展到所需的版本，或者更好的是您可以在其 GitHub 存储库上提出问题。

Which hardhat vyper version supports it? I will directly modify it to that version.

**Comment by liny52** [comment]
> Hey @liny52, this error is raised from the newest version of the Hardhat Vyper plugin (@nomiclabs/hardhat-vyper@3.0.3), which our Hardhat plugin for Vyper (@matterlabs/hardhat-zksync-vyper) relies on. Currently, it appears that the specific Vyper version you're using isn't supported by this plugin. (you can find list of supported vyper versions [here](https://vyper-releases-mirror.hardhat.org/list.json)). At the moment, the best course of action would be to either wait for the plugin to extend its support to the required versions, or even better you can open an issue on their GitHub repository.

Which hardhat vyper version supports it? I will directly modify it to that version.

**Comment by mpopovac-txfusion** [comment]
The zkvyper compiler supports the following versions of Vyper: `0.3.3`, `0.3.8`, and `0.3.9`. However, since the latest version supported by hardhat-vyper (until now) is `0.3.7`, I would recommend using Vyper version `0.3.3`.
