### ISSUE TITLE
hardhat-zksync-verify doesn't support verifying UUPS Proxy

### ISSUE THREAD

**Issue by nicholaspai** [matter-labs/hardhat-zksync#337]
I was able to deploy a UUPS proxy and implementation and upgrade the proxy to the implementation. In addition I've verified the implementation via `hardhat verify`. However, I'm unable to verify the proxy: 

> Error in plugin @nomiclabs/hardhat-etherscan: Trying to verify a contract in a network with chain id 280, but the plugin doesn't recognize it as a supported chain.

I wonder if this is because `uupsUpgradeableProxy` isn't explicitly listed [here](https://github.com/matter-labs/hardhat-zksync/blob/main/packages/hardhat-zksync-upgradable/src/constants.ts#L39)?

**Comment by FilipTxFusion** [comment]
Hi @nicholaspai, our verify plugin supports UUPS proxy verification, but from the error you submitted it seems that you are not using `@matterlabs/hardhat-zksync-verify` plugin, but `@nomiclabs/hardhat-etherscan` instead.
Both of those are necessary to install, but in your hardhat.config file you should import `hardhat-zksync-verify` as explained [here](https://era.zksync.io/docs/tools/hardhat/hardhat-zksync-verify.html#setup).

Let me know if we can help any further.

**Comment by nicholaspai** [comment]
Ah I see this did work in the end once I switched the dep from `nomiclabs/hardhat-etherscan` to `nomicfoundation/hardhat-verify`
