### ISSUE TITLE
The hardhat-zksync-solc complie is to large than solidity 0.8.19 

### ISSUE THREAD

**Issue by tiantianlikeu** [matter-labs/hardhat-zksync#340]
zksolc: {
    version: "latest",
    compilerSource: "binary",
    settings: {
      optimizer: {
        enabled: true, // optional. True by default
        mode: 'z', // optional. 3 by default, z to optimize bytecode size
        runs: 200
      },
    },
  },
 solidity: {
    version: "0.8.19",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  },

using zksolc complied size is 58.406 KB
using solidity compiled size is 18.924 KB

**Comment by mpopovac-txfusion** [comment]
Hey @tiantianlikeu! I noticed you've been comparing the outputs of solc and zksolc, and it seems that zksolc's compiled size output is indeed bigger. However, based on the comments you added in the optimizer config section, it's clear that you're specifically interested in comparing outputs when the mode is set to `3` or `z`. So make sure to focus on those configurations for a more accurate comparison.

**Comment by tiantianlikeu** [comment]
@mpopovac-txfusion  Hey ! I want them to be about the same size, how to optimize the configuration, I looked at the documentation, zksolc optimizer is already z.
help me
