### ISSUE TITLE
hardhat-zksync-upgradable: What are the contracts that deployed at `defaultImplAddresses` constants?

### ISSUE THREAD

**Issue by anhlh-edsolabs** [matter-labs/hardhat-zksync#348]
Hi, 
I'm trying to deploy upgradeable contracts on my own Zksync network and stumbled upon this issue. The function `estimateGasProxy` looks for `mockImplAddress` by from a constant object:
https://github.com/matter-labs/hardhat-zksync/blob/70b878cbab2edc9027fc1236a30106af26faa3bf/packages/hardhat-zksync-upgradable/src/gas-estimation/estimate-gas-proxy.ts#L53C9-L60C10

```
        if (chainId == 270) {
            const adminFactory = await getAdminFactory(hre, deployer.zkWallet);
            mockImplAddress = await deployProxyAdminLocally(adminFactory);
            data = getInitializerData(adminFactory.interface, args, opts.initializer);
        } else {
            mockImplAddress = defaultImplAddresses[chainId].contractAddress;
            data = getInitializerData(ethers.Contract.getInterface(mockArtifact.abi), args, opts.initializer);
        }
```
which in turns defined here: 
https://github.com/matter-labs/hardhat-zksync/blob/70b878cbab2edc9027fc1236a30106af26faa3bf/packages/hardhat-zksync-upgradable/src/constants.ts#L47C1-L56C3
```
export const defaultImplAddresses: { [chainId in number]: { contractAddress: string; beacon: string } } = {
    324: {
        contractAddress: '0x71CF3E1430aA920903CeF2154202902dDbBE2c98',
        beacon: '0x3DbAe90affFFAC8d20285f2f53e3f2e10368c11C',
    },
    280: {
        contractAddress: '0xCFFF2D44a3d3361f86Aa9EA5c563B95FAcA7be8c',
        beacon: '0x713499530cCAc7a09FecFf05C3a1d4413E4CCd12',
    },
};
```
Since my custom network's chainID is neither 324 nor 280, the gas estimation failed and cause the deployment to fail.
I'd like to know which contracts are deployed at those address, so I can deploy the same contracts on my own network to let the gas estimation works. 

Thanks a lot in advance.

**Comment by FilipTxFusion** [comment]
Hi @anhlh-edsolabs, you can deploy any kind of a simple contract (for example ProxyAdmin.sol contract) and use its address in the gas estimation function since it is only needed for the initializer data mocking and does not significantly impact the returned gas value.

**Comment by anhlh-edsolabs** [comment]
> Hi @anhlh-edsolabs, you can deploy any kind of a simple contract (for example ProxyAdmin.sol contract) and use its address in the gas estimation function since it is only needed for the initializer data mocking and does not significantly impact the returned gas value.

Thanks @FilipTxFusion for your help! It took me a while to figure out how to properly get the initializerData to pass to the `estimateDeployFee` function. Works perfectly now.
