### ISSUE TITLE
Unable to verify transparent proxy contracts with zksync-verify

### ISSUE THREAD

**Issue by waynehoover** [matter-labs/hardhat-zksync#351]
I have deployed a transparent proxy contract with the upgrades plugin with `hre.zkUpgrades.deployProxy` but when I try and verify the proxy contract I get this error.

`Error in plugin @matterlabs/hardhat-zksync-verify: The number of constructor arguments you provided (0) does not match the number of constructor arguments the contract has been deployed with (3)`

What are the constructor arguments I need to pass? I assume they are the proxy creation arguments. Verifying the admin and implementation contract worked fine.

**Comment by FilipTxFusion** [comment]
Hi @waynehoover , you don't have to verify each smart contract separately. Our verify plugin supports out of box verification for all the contracts included in the proxy deployment process. You can find more info on this [link](https://era.zksync.io/docs/tools/hardhat/hardhat-zksync-upgradable.html#proxy-verification). 

Let us know if you need any additional help.
