### ISSUE TITLE
hardhat-zksync-verify  How to verify open source upgradable contracts

### ISSUE THREAD

**Issue by contractsolidity** [matter-labs/hardhat-zksync#358]

**Comment by FilipTxFusion** [comment]
Hi @contractsolidity, you can use our hardhat-zksync-upgradable plugin to verify upgradable smart contracts.
Find more details on how to run the verification process in the official [documentation](https://era.zksync.io/docs/tools/hardhat/hardhat-zksync-upgradable.html#proxy-verification).
