### ISSUE TITLE
hardhat-zksync-upgradable: Need a `defaultFallbackName` for unknown network manifest file.

### ISSUE THREAD

**Issue by anhlh-edsolabs** [matter-labs/hardhat-zksync#360]
Hi,
I've been using this plugin to deploy upgradeable contracts on my private zkSync networks and this issue arises:
- My private network's chainIDs are not support/defined in [packages/hardhat-zksync-upgradable/src/core/provider.ts](https://github.com/matter-labs/hardhat-zksync/blob/f5c7e4a8b39196fb493785c71eef6c21d1c585ae/packages/hardhat-zksync-upgradable/src/core/provider.ts), for example **54321** and **34567**
- When the Manifest object is initialized, it looks for the network names that are bound with those chainIDs but didn't found one, and render a file `undefined.json` in the `.upgradable` folder.
- When contracts are deployed to different networks, the data is written to the same `undefined.json` file and existing data could be overwritten.

To deal with the problem, I suggest that we add a `DefaultFallbackName` in the Manifest class constructor here: ([packages/hardhat-zksync-upgradable/src/core/manifest.ts](https://github.com/matter-labs/hardhat-zksync/blob/f5c7e4a8b39196fb493785c71eef6c21d1c585ae/packages/hardhat-zksync-upgradable/src/core/manifest.ts#L59C5-L66C6), so we'll have different manifest files for different `unknown` networks
```Javascript
constructor(chainId: number) {
        this.chainId = chainId;
        this.chainIdSuffix = `${chainId}`;

        this.dir = MANIFEST_DEFAULT_DIR;
        
        const defaultFallbackName = `unknown-${chainId}`;
        const networkName = networkNames[chainId] !== undefined ? networkNames[chainId] : defaultFallbackName;


        this.file = path.join(MANIFEST_DEFAULT_DIR, `${networkName}.json`);
}
```

**Comment by nikola-bozin-txfusion** [comment]
Hello @anhlh-edsolabs , we have made the required updates and it will be released with next version of plugin.
Closing the issue.
