### ISSUE TITLE
vyper verify contarct

### ISSUE THREAD

**Issue by richiezk** [matter-labs/hardhat-zksync#388]
The deployment script added verification code, but the verification was still unsuccessful.

  await hre.run("verify:verify:vyper", {
    address: contractAddress,
    // contract: artifact.contractName,
    constructorArguments: [],
  });

<img width="1284" alt="image" src="https://github.com/matter-labs/hardhat-zksync/assets/69138618/73060856-af98-42a3-8882-1ae88367020b">
<img width="869" alt="image" src="https://github.com/matter-labs/hardhat-zksync/assets/69138618/43ebc031-a5df-4b34-b1d4-dffbb2f4dcec">

**Comment by FilipTxFusion** [comment]
Hi @richiezk, did you run the verify command right after the deployment of the smart contract?
If you did, can you provide more context about the contract you are trying to verify (its source code, hardhat config, deploy script you used, etc) ?
