### ISSUE TITLE
If you move the hardhat.config.ts from the defaul root folder the deploy package never found the deploy folder - @matterlabs/hardhat-zksync-deploy

### ISSUE THREAD

**Issue by ogarciarevett** [matter-labs/hardhat-zksync#422]
Bug: If you move the **hardhat.config.** to be used in a different **folder**, the deploy package is always trying to get the deploys from the absolute path of "./deploy" and in these cases will fails because the zkSync.config.ts is not in the root.

_Structure folders example:_
```bash
├── CHANGELOG.md
├── README.md
├── configs
│   ├── hardhat.config.ts
│   ├── Y.config.ts
│   ├── X.config.ts
│   └── zkSync.config.ts
├── deploy
│   ├── deployX.ts
│   └── deployY.ts
├── package-lock.json
├── package.json
```

**command**:

`npx hardhat --config ./configs/zkSync.config.ts deploy-zksync --network zkSyncTestnet --script deployX.ts`

or

`npx hardhat --config ./configs/zkSync.config.ts deploy-zksync --network zkSyncTestnet --script deploy/deployX.ts`

It always returns this error:

![Screenshot 2023-10-14 at 20 54 41](https://github.com/matter-labs/hardhat-zksync/assets/12629920/af9a669c-82aa-4782-9937-75ca47645bc6)

If someone else needs to use this too, just moving the zkSync.config.ts will remove the error, but the structure of the project will be a little bit ugly.

**Comment by kiriyaga** [comment]
Thanks for reporting this issue.
When we set the config path with hardhat --config, the root path is calculated from that path, and all the things specified for hardhat will be calculated from there (artifact, cache, deployment script...). My suggestion is that your hardhat file is always in the root folder and then can import sub configs there and use them (maybe with some if statement for different networks).
In the future, we will make the deploy path more flexible so it can be used independently of the root path.
