### ISSUE TITLE
Using non-latest version of the zksolc is not working with the ECSA for verify signatures - @matterlabs/hardhat-zksync-zksolc 

### ISSUE THREAD

**Issue by ogarciarevett** [matter-labs/hardhat-zksync#423]
This is my current implementation to recover a signature using a nonce and external signature provided for gasless / public operations, this is working perfectly on `"@matterlabs/hardhat-zksync-solc": "^0.4.2"` but for the rest of the previous versions is not working at all. 

The main issue that I have now is that We want to use this with a Paymaster, like both things at the same time to do specific and custom stuff, but the paymaster brokes the build in the latest **zksolc** version. So, sadly I'm in the middle of two walls lol.

1. if I use the latest version, zkSolc works with the ECDSA stuff but the paymaster doesn't work for the erc20 and nft gating things.

2. If I downgrade the versions the ECDSA stuff doesn't work but the paymaster works perfectly. 

ECDSA function that We use to recover an Address and do a verification later:

```solidity
function recoverAddress(uint256 nonce, bytes memory signature) private view returns (address) {
    bytes32 message = keccak256(abi.encodePacked(msg.sender, nonce));
    bytes32 hash = ECDSA.toEthSignedMessageHash(message);
    address signer = ECDSA.recover(hash, signature);
    return signer;
  }
```

**Comment by idea404** [comment]
Hi @ogarciarevett could you also share the exact versions of everything including `zksolc`?

**Comment by githubdoramon** [comment]
> Hi @ogarciarevett could you also share the exact versions of everything including `zksolc`?

@ogarciarevett pls share any (and all) information you can :) 

- Full hardhat.config.js
- What exactly "paymaster doesn't work" means
- What exactly "ECDSA" signature doesn't work means
- Any compilation config you are setting somewhere other than hardhat config?

Would be great if you could set up a minimum reproducible repo so we can debug it as well.

Many thanks

**Comment by ogarciarevett** [comment]
> Hi @ogarciarevett could you also share the exact versions of everything including `zksolc`?

The `0.4.2` in the package version that I used in the signature check

and the `0.4.0` in the paymaster

I'll share the full hardhat file for the paymaster project
``` typescript
const config: HardhatUserConfig = {
  solidity: {
    version: '0.8.17',
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
  defaultNetwork: 'hardhat',
  zksolc: {
    version: 'latest',
    settings: {
      optimizer: {
        mode: '3', // optional. 3 by default, z to optimize bytecode size
      },
    },
  },
  networks: {
    hardhat: {
      zksync: false,
      blockGasLimit: 3_00_000_000,
    },
    mainnet: {
      url: `https://mainnet.infura.io/v3/${INFURA_API_KEY}`,
      zksync: false,
    },
    goerli: {
      url: `https://goerli.infura.io/v3/${INFURA_API_KEY}`, // The Ethereum Web3 RPC URL (optional).
      zksync: false,
    },
    zkSync: {
      url: 'https://mainnet.era.zksync.io',
      ethNetwork: 'mainnet',
      zksync: true,
      accounts: [DEPLOYER_PRIVATE_KEY || PRIVATE_KEY],
      verifyURL: 'https://zksync2-mainnet-explorer.zksync.io/contract_verification',
    },
    zkSyncTestnet: {
      url: 'https://zksync2-testnet.zksync.dev',
      ethNetwork: 'goerli',
      zksync: true,
      accounts: [DEPLOYER_PRIVATE_KEY || PRIVATE_KEY],
      verifyURL: 'https://zksync2-testnet-explorer.zksync.dev/contract_verification',
    }
  }
};
```

The ECDSA doesn't work because in the moment that recover a nonce and signture from this functions, returns a different address in the old versions of the `zksolc` package

```solidity
function recoverAddress(uint256 nonce, bytes memory signature) private view returns (address) {
    bytes32 message = keccak256(abi.encodePacked(msg.sender, nonce));
    bytes32 hash = ECDSA.toEthSignedMessageHash(message);
    address signer = ECDSA.recover(hash, signature);
    return signer;
  }
```

**Comment by hedgar2017** [comment]
Hey @ogarciarevett, unfortunately, this information isn't very helpful to us, and we need a minimal reproducible example as a repo we can run.
We have no tools to debug an extracted piece of a large project like this one.

Additionally, please include error messages for all errors you're having.
Thanks!

**Comment by ogarciarevett** [comment]
I found a simple work around working with a different repo, one for the paymaster and another one for the contracts that needs the signatures in the latest version of the zkSolc
