### ISSUE TITLE
Latest zkSolc version is not working with the verification package

### ISSUE THREAD

**Issue by ogarciarevett** [matter-labs/hardhat-zksync#427]
Hi guys, I was working and deploying a new contracts and I found an error trying to verify the contracts using the latest version of zkSolc

![Screenshot 2023-10-23 at 21 21 27](https://github.com/matter-labs/hardhat-zksync/assets/12629920/36b5f7f5-1863-432b-841a-2bd44bb33265)

![Screenshot 2023-10-23 at 21 16 51](https://github.com/matter-labs/hardhat-zksync/assets/12629920/f8a3fee4-1915-45b2-9629-2769b441ab89)

If I just go back to the 1.3.14 version everything works.

**Comment by kiriyaga** [comment]
Hello @ogarciarevett ,
Check this out: https://zksync2-testnet-explorer.zksync.dev/contract_verification/43899
An error is received on the BE side during verification, where the new version is still unknown. We notice this issue and it will be resolved asap.

**Comment by ogarciarevett** [comment]
Hi! Same error but bow with the latest version `v1.3.17`
![Screenshot 2023-11-17 at 13 33 25](https://github.com/matter-labs/hardhat-zksync/assets/12629920/6d971b59-9be9-4335-bf84-321b0b4dee7e)
