### ISSUE TITLE
Bump `@nomicfoundation/hardhat-verify` to Version `2.0.0`

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/hardhat-zksync#476]
Hey guys, I'm confused:

In [this](https://github.com/matter-labs/hardhat-zksync/commit/2841aa9f7d21a08af368037073051fc8d5c573e1) commit you bump the peer dependency `@nomicfoundation/hardhat-verify` to version `2.0.0`, and one commit later (https://github.com/matter-labs/hardhat-zksync/commit/b3b175b9d4b529f86d6b7b56e73cd734da40c1c6) you revert that change.

I would really appreciate if you could bump the `@nomicfoundation/hardhat-verify` peer dependency and make a new release as I depend on the new sourcify feature this version entails and (again) zkSync dependencies holding me back to upgrade it...

**Comment by nikola-bozin-txfusion** [comment]
Hello, we are working on it and it will be released during the weekend or early next week.
I will give you an update as soon as it's released.

**Comment by pcaversaccio** [comment]
> Hello, we are working on it and it will be released during the weekend or early next week.
> I will give you an update as soon as it's released.

Appreciate the effort!

**Comment by nikola-bozin-txfusion** [comment]
@pcaversaccio The new version has been released. Please check and inform me if you encounter any issues.

**Comment by pcaversaccio** [comment]
> @pcaversaccio The new version has been released. Please check and inform me if you encounter any issues.

Looks like it worked (example verification: https://goerli.explorer.zksync.io/address/0x6Cb4315C7d347615E3461516FE1FA81Fad49bCF8#contract), but I got a provider error that wasn't here before (please ignore the Truffle error):

```
> hardhat-project-template-ts@1.0.0 deploy:zksynctestnet C:\Dev\Blockchain\hardhat-project-template-ts
> npx hardhat deploy-zksync --network zkSyncTestnet --script deploy-zksync.ts

ProviderError: Failed to serialize transaction: toAddressIsNull
    at HttpProvider.request (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\hardhat@2.19.1_ts-node@10.9.1_typescript@5.3.2\node_modules\hardhat\src\internal\core\providers\http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HardhatEthersProvider.estimateGas (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@nomicfoundation+hardhat-ethers@3.0.5_ethers@6.8.1_hardhat@2.19.1\node_modules\@nomicfoundation\hardhat-ethers\src\internal\hardhat-ethers-provider.ts:237:27)
    at async C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@nomicfoundation+hardhat-ethers@3.0.5_ethers@6.8.1_hardhat@2.19.1\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:235:35
    at async Promise.all (index 0)
    at async HardhatEthersSigner._sendUncheckedTransaction (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@nomicfoundation+hardhat-ethers@3.0.5_ethers@6.8.1_hardhat@2.19.1\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:256:7)
    at async HardhatEthersSigner.sendTransaction (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@nomicfoundation+hardhat-ethers@3.0.5_ethers@6.8.1_hardhat@2.19.1\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:125:18)
    at async ContractFactory.deploy (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\ethers@6.8.1\node_modules\ethers\src.ts\contract\factory.ts:111:24)
    at async main (C:\Dev\Blockchain\hardhat-project-template-ts\scripts\deploy.ts:9:20)
Greeter deployed to: 0x6Cb4315C7d347615E3461516FE1FA81Fad49bCF8
Preparing Truffle compilation
The Truffle Dashboard plugin failed to compile:  TypeError: Cannot read properties of undefined (reading 'sourceMap')
    at Object.Contracts.fromBuildInfo (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@truffle+from-hardhat@0.2.20\node_modules\@truffle\from-hardhat\src\compilation.ts:70:57)    
    at Object.fromBuildInfo (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@truffle+from-hardhat@0.2.20\node_modules\@truffle\from-hardhat\src\compilation.ts:12:26)
    at C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@truffle+from-hardhat@0.2.20\node_modules\@truffle\from-hardhat\src\api.ts:165:37
    at Generator.next (<anonymous>)
    at fulfilled (C:\Dev\Blockchain\hardhat-project-template-ts\node_modules\.pnpm\@truffle+from-hardhat@0.2.20\node_modules\@truffle\from-hardhat\dist\src\api.js:28:58)
 ·------------------------|--------------------------------|--------------------------------·
 |  Solc version: 0.8.21  ·  Optimizer enabled: true       ·  Runs: undefined               │
 ·························|································|·································
 |  Contract Name         ·  Deployed size (KiB) (change)  ·  Initcode size (KiB) (change)  │
 ·························|································|·································
 |  Create2               ·                 0.219 (0.000)  ·                 0.219 (0.000)  │
 ·························|································|·································
 |  Create2Deployer       ·                 6.031 (0.000)  ·                 6.031 (0.000)  │
 ·························|································|·································
 |  Create2DeployerLocal  ·                 6.031 (0.000)  ·                 6.031 (0.000)  │
 ·························|································|·································
 |  ERC1820Implementer    ·                 0.906 (0.000)  ·                 0.906 (0.000)  │
 ·························|································|·································
 |  Greeter               ·                 4.094 (0.000)  ·                 4.094 (0.000)  │
 ·------------------------|--------------------------------|--------------------------------·
Your verification ID is: 47368
Contract successfully verified on zkSync block explorer!
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by pcaversaccio** [comment]
@nikola-bozin-txfusion can you maybe explain where the error:

```bash
ProviderError: Failed to serialize transaction: toAddressIsNull
```

is coming from? I found some other people facing the same issue using e.g. Remix: https://ethereum.stackexchange.com/questions/150695/how-to-deploy-smart-contract-on-zksync-era-testnet-using-remix-and-metamask

**Comment by nikola-bozin-txfusion** [comment]
@pcaversaccio could you please provide me with your project repository for the deployment script so I can replicate it?

**Comment by pcaversaccio** [comment]
> @pcaversaccio could you please provide me with your project repository for the deployment script so I can replicate it?

Sure: https://github.com/pcaversaccio/hardhat-project-template-ts

In order to make it work, you have to change the zksolc version `1.3.17` to `1.3.16` [here](https://github.com/pcaversaccio/hardhat-project-template-ts/blob/main/hardhat.config.ts#L86), and change to solc version to `0.8.21` [here](https://github.com/pcaversaccio/hardhat-project-template-ts/blob/main/hardhat.config.ts#L76) and [here](https://github.com/pcaversaccio/hardhat-project-template-ts/blob/main/contracts/src/Greeter.sol#L2). Note that I don't use `dotenv` variables any more, but [Hardhat configuration variables](https://github.com/pcaversaccio/hardhat-project-template-ts/tree/main?tab=readme-ov-file#configuration-variables). That's why the zksync deployment [script](https://github.com/pcaversaccio/hardhat-project-template-ts/blob/main/deploy/deploy-zksync.ts) is slightly adjusted for this.

**Comment by kiriyaga-txfusion** [comment]
Hello @pcaversaccio, it seems that in 'deploy/deploy-zksync.ts' script you imported the deploy function from 'script/deploy.ts', and during that import, the main function in that script also started, and that's why you got that error. My recommendation is to separate that helper function into a helper file to avoid that problem.

**Comment by pcaversaccio** [comment]
> Hello @pcaversaccio, it seems that in 'deploy/deploy-zksync.ts' script you imported the deploy function from 'script/deploy.ts', and during that import, the main function in that script also started, and that's why you got that error. My recommendation is to separate that helper function into a helper file to avoid that problem.

Oh I see, that makes sense. Will adjust accordingly, thx!
