### ISSUE TITLE
Bump `zksync2-js` Peer Dependency to `^0.4.0`

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/hardhat-zksync#497]
As title. The following dependencies use the older version of `zksync2-js`:
- `hardhat-zksync-zksync2js`
- `hardhat-zksync-deploy`

**Comment by pcaversaccio** [comment]
Any update on this @nikola-bozin-txfusion?

**Comment by nikola-bozin-txfusion** [comment]
@pcaversaccio Yes, the update is already in one of our PRs and its getting ready to be merged.

**Comment by pcaversaccio** [comment]
> @pcaversaccio Yes, the update is already in one of our PRs and its getting ready to be merged.

Sweet, thanks for the heads-up!

**Comment by nikola-bozin-txfusion** [comment]
Yes, we know, we are making the required changes for the next release!

**Comment by pcaversaccio** [comment]
Looks like the latest releases fix this issue, thx!

**Comment by nikola-bozin-txfusion** [comment]
@pcaversaccio Hey, we did bump the dependency, but now we recommend using `zksync-ethers` instead of `zksync2-js`.

**Comment by pcaversaccio** [comment]
Thanks already switched: https://github.com/pcaversaccio/hardhat-project-template-ts/commit/5b71d7d43b5c4b6dd572b491467367694213484c.

One question: Why does `@matterlabs/hardhat-zksync-deploy` not support anymore the provision of RPC URLs for `ethNetwork`? I had to switch to the supported network names to make it work...

**Comment by pcaversaccio** [comment]
If you use an RPC URL with the latest version, you will get:

```bash
cannot read properties of undefined (reading 'url')
```
