### ISSUE TITLE
Bug: `hardhat-zksync-zksync2js` version `0.0.1-beta.0` build is broken on `npm`

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/hardhat-zksync#498]
The current `latest` tagged version of `hardhat-zksync-zksync2js` has a broken build on [`npm`](https://www.npmjs.com/package/@matterlabs/hardhat-zksync-zksync2js?activeTab=versions) since the `dist` folder is missing in the uploaded package and thus you can't access any `hre.zksync2js` objects. If you upgrade to the latest beta version `0.0.1-beta.2`, it will fix the issue but this version doesn't have the `latest` tag and thus people using the default `npm` install will face issues.

**Comment by kiriyaga-txfusion** [comment]
Hello @pcaversaccio , we added the **latest** tag to release 0.0.1-beta.2, so you won't have that problem anymore. Thanks.
