### ISSUE TITLE
I ran the contract verify task "verify:verify", I got the error "Error in plugin @matterlabs/hardhat-zksync-verify: Unknown zksolc version: v1.3.17"

### ISSUE THREAD

**Issue by crazytang** [matter-labs/hardhat-zksync#501]
The error msg is from https://zksync2-testnet-explorer.zksync.dev/contract_verification/47428.

Is it a bug? or someone tell me how to fix the problem?

**Comment by nikola-bozin-txfusion** [comment]
@crazytang Hey, the v1.3.17 is now supported on the backend. You can now send your contracts for verification compiled with 1.3.17 version.
Closing the issue.
