### ISSUE TITLE
CI Not Being Respected

### ISSUE THREAD

**Issue by idea404** [matter-labs/hardhat-zksync#509]
The CI has been failing for [the past three weeks](https://github.com/matter-labs/hardhat-zksync/commits/main) and there have been several commits to `main` in the meantime, none addressing the broken pipeline. Let's please use the CI for what it's meant for: as an automation that should tell about the proper functioning of the code in the repository.

**Comment by nikola-bozin-txfusion** [comment]
@idea404 Since the dockerized setup has been fixed, the CI will be respected in upcoming changes.
Here is one of the actions: https://github.com/matter-labs/hardhat-zksync/actions/runs/7182926066
