### ISSUE TITLE
Cannot verify contracts compiled with zksolc v1.3.18

### ISSUE THREAD

**Issue by kbortnik** [matter-labs/hardhat-zksync#569]
#### 💥 Plugin name

@matterlabs/hardhat-zksync-verify

#### 📝 Description

Verifying contracts compiled with zksolc v1.3.18 fails.

#### 🔄 Reproduction Steps

1. Set zksolc version to 1.3.18 (or in my case `latest`)
2. Compile and deploy contract
3. Attempt to verify with `hardhat verify`

#### 🤔 Expected Behavior

Contract is verified.

#### 😯 Current Behavior

Verification fails.

#### 🖥️ Environment

macOS, pnpm on node 20.6.1

#### 📋 Additional Context

[https://zksync2-mainnet-explorer.zksync.io/contract_verification/36653](https://zksync2-mainnet-explorer.zksync.io/contract_verification/36653)

#### 📎 Log Output

```
Your verification ID is: 36653
Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Unknown zksolc version: v1.3.18
```

**Comment by kbortnik** [comment]
Seems like this issue regresses pretty much any time zksolc is updated, so the backend verification system is usually behind.
1.3.14:
https://github.com/matter-labs/hardhat-zksync/issues/427
1.3.17:
https://github.com/matter-labs/hardhat-zksync/issues/501

**Comment by nikola-bozin-txfusion** [comment]
Yes, the issues are related. The backend system does not yet support zksolc v1.3.18 for verification.
The hotfix here is to put the version in your hardhat.config file to 1.3.17 as that's the highest supported version for now.

**Comment by nikola-bozin-txfusion** [comment]
@kbortnik You can now verify contracts compiled with zksolc 1.3.18.
 Closing the issue.
