### ISSUE TITLE
zkSync Era Solidity Version Support

### ISSUE THREAD

**Issue by idea404** [matter-labs/hardhat-zksync#596]
### 🌟 Feature Request for hardaht-zksync plugins

The ML compiler team has released an own version of [the solc compiler](https://github.com/matter-labs/era-solidity) meant to address the limitations from solc <0.8 and solc >=0.8 versions using the old codegen as explained [here](https://era.zksync.io/docs/tools/compiler-toolchain/solidity.html#limitations).

Can this also please be included as a feature in the plugins?

Such that developers can specify this in their `hardhat.config.ts` files, as for example:

```ts
{
  ...
  solidity: {
    version: "0.8.17",
    era-version: "1.0.0"
  },
  ...
}
```

And if it is not specified, the plugins use the conventional solidity compiler.

----

Edit: Changed `"latest"` to `"1.0.0"` in `era-version`. Better to have developers be explicit about the version they wish to use in config

**Comment by kiriyaga-txfusion** [comment]
EraVm support has been successfully integrated into hardhat-zksync-solc, starting from version 1.1.0 and onwards.
