### ISSUE TITLE
Error when verifying zksync testnet

### ISSUE THREAD

**Issue by huuhoa143** [matter-labs/hardhat-zksync#654]
I met this error 
```
Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Unknown zksolc version: v1.3.19
```
When verifying contract using zksolc latest (v1.3.19) and solc (v0.8.17), using "https://explorer.sepolia.era.zksync.dev/contract_verification" verifyURl

**Comment by nikola-bozin-txfusion** [comment]
Hello @huuhoa143, version 1.3.19 is currently not supported. 
A hotfix is to set the zksolc version to 1.3.18 for example, in your hardhat config.

I will be informing you once the version is supported.

**Comment by nikola-bozin-txfusion** [comment]
Hello @huuhoa143, the version 1.3.19 is now supported and should not throw an error.
Closing the issue now.
