### ISSUE TITLE
Hardhat ignores hardhat-zksync-solc plugin

### ISSUE THREAD

**Issue by saumenestrello** [matter-labs/hardhat-zksync#66]
Hello,
I'm following [this tutorial](https://v2-docs.zksync.io/api/hardhat/getting-started.html) to setup a zkSync hardhat project from scratch. When I run `yarn hardhat compile` it seems to run the standard hardhat task, there is no `tmp` folder. 

If I run `yarn hardhat deploy-zksync` to execute the deploy script, it throws an error on
```
await deployer.loadArtifact("Greeter");
```
saying **"Error in plugin @matterlabs/hardhat-zksync-solc: Artifact Greeter was not compiled by zksolc"**.
Any idea on what can cause this issue?

**Comment by ly0va** [comment]
Hi @saumenestrello, thanks for reaching out! The stuff about the `tmp` folder in the tutorial is outdated - there shouldn't be one. We'll update the tutorial soon.

Please share the version of `hardhat-zksync-solc` you're using so we can get an idea of what might be going on.

**Comment by saumenestrello** [comment]
Hi @ly0va, thanks for the reply. I'm using version **0.3.0** of `hardhat-zksync-solc`

**Comment by saumenestrello** [comment]
Thank you @ly0va, I don't see that error anymore. 

On Ubuntu I was able to run `yarn hardhat compile` with no errors, whereas on Windows the command throws the following error 
```
Error in plugin @matterlabs/hardhat-zksync-solc: Docker Desktop is not installed.
Please install it by following the instructions on https://www.docker.com/get-started
```
even if I have the last version of Docker Desktop installed. I thought you might want to look into that, I'm not sure if this should be a different issue tho

**Comment by ly0va** [comment]
Thanks for the feedback! Currently, the plugins only work on WSL2 (if you want to use Windows). We're investigating the possibility of native Windows support.
