### ISSUE TITLE
Zksync Sepolia is missing from upgradable package

### ISSUE THREAD

**Issue by clemsos** [matter-labs/hardhat-zksync#696]
#### 💥 Plugin name

hardhat-zksync-upgradable

#### 📝 Description

Sepolia is missing from the supported networks list in the upgradable package, causing the manifest file to be saved as `undefined.json`

#### 🔄 Reproduction Steps

1. Step 1 : use the `deployProxy` function on zksync sepolia
2. Step 2: check that `.upgradable/undefined.json` exists

#### 🤔 Expected Behavior

The manifest file should be sth like `.upgradable/zksync-sepolia.json`

#### 😯 Current Behavior

The manifest file is saved as `.upgradable/undefined.json`

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📋 Additional Context

Maybe add the network here

https://github.com/matter-labs/hardhat-zksync/blob/main/packages/hardhat-zksync-upgradable/src/core/provider.ts#L8-L11

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by nikola-bozin-txfusion** [comment]
Hello @clemsos, we are aware that Sepolia network is missing and we will be having this supported in next release.

**Comment by nikola-bozin-txfusion** [comment]
Hey @clemsos, the Sepolia testnet has been added and available with the latest version of `hardhat-zksync-upgradable` plugin.
Closing.

**Comment by clemsos** [comment]
great thank you @nikola-bozin-txfusion !
