### ISSUE TITLE
hardhat-zksync-verify-v0.5.0 release not available on NPM

### ISSUE THREAD

**Issue by stevyhacker** [matter-labs/hardhat-zksync#706]
#### 📝 Description

The release from the github releases page https://github.com/matter-labs/hardhat-zksync/releases/tag/%40matterlabs%2Fhardhat-zksync-verify-v0.5.0 is not available to download from NPM.

Does this version make the verification possible on the zksync era for contracts compiled with zksolc 1.3.22 and solc v0.8.19?

**Comment by nikola-bozin-txfusion** [comment]
Hello @stevyhacker  , the 0.5.0 version should be released shortly.
The version 0.5.0 adds support for zkvm solc compiler verification on ethers-v5.
Contract verification using zksolc `1.3.22` and solc `0.8.19` should work, could you please try again?

**Comment by stevyhacker** [comment]
I'm using ethers-v5 

The error I get is a bit unclear to me what is the cause.

I run the script like this: `hh verify --network zkMainnet 0xC5cE5BfFF3cc7e255A25c7636eE9646FCdF86f57 0x5771E319184E01Ac3BB611369E837daa9376fBf1`

and get this

```
Successfully compiled 67 Solidity files
An unexpected error occurred:

Error: ENOENT: no such file or directory, open '/Users/stevyhacker/Documents/GitHub/lending-smart-contracts/artifacts-zk/build-info/45617246a604efb207c3ce3e22d780a5.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/stevyhacker/Documents/GitHub/lending-smart-contracts/artifacts-zk/build-info/45617246a604efb207c3ce3e22d780a5.json'
}
```

**Comment by nikola-bozin-txfusion** [comment]
@stevyhacker, is there a way i can replicate this?

**Comment by stevyhacker** [comment]
Yes, you can try running this script to deploy a contract and then use the above command to try to verify it. https://github.com/zkFinance/lending-smart-contracts/blob/master/deploy/deploy-zkfinance-oracle.ts

**Comment by stevyhacker** [comment]
Sorry I forgot it's private, I resolved this issue on my own later, it was a hardhat config problem.
Closing this issue now.
