### ISSUE TITLE
Impossible to import `Deployer` after adding upgradable lib to hardhat config

### ISSUE THREAD

**Issue by clemsos** [matter-labs/hardhat-zksync#711]
#### 💥 Plugin name

hardhat-zksync-upgradable / hardhat-zksync-deploy

#### 📝 Description

When requiring the `deploy` lib in a different file after adding the `upgradeable` to hardhat config, the lib attempts to redefine hardhat tasks which throws to the following error 

```
Error HH209: Redefinition of task deploy-zksync failed. Unsupported operation adding mandatory (non optional) param definitions in an overridden task.

```

#### 🔄 Reproduction Steps

1. Step 1: in `hardhat.config.js` : require('hardhat-zksync-upgradable')
2. Step 2: in separate file : `const { Deployer } = require('hardhat-zksync-deploy')` (tested in separate monorepo package)
3. throw the following error 

```
Error HH209: Redefinition of task deploy-zksync failed. Unsupported operation adding mandatory (non optional) param definitions in an overridden task.

For more info go to https://hardhat.org/HH209 or run Hardhat with --show-stack-traces```
```

#### 🤔 Expected Behavior

Should be able to import the `Deployer` class.

#### 😯 Current Behavior

Impossible to import the `Deployer` class in a separate monorepo package.

#### 📋 Additional Context

I have added the following workaround https://github.com/unlock-protocol/unlock/pull/13078/commits/3b08b5a87776efe61e211f57f8aca7fb8bc75f9c which is not ideal but fixes the issue if I use `1.2.0` but will fail with `1.2.2`.

**Comment by kiriyaga** [comment]
It seems that in our examples, everything is works. However, in your project, we observed that hardhat imports hardhat-zksync-deploy twice index.ts, which leads to the error you encountered. To address this issue, you can use the following workaround within the helper package:

`const { Deployer } = require('@matterlabs/hardhat-zksync-deploy/dist/deployer');`

We'll dedicate some time to investigating why this duplication occurs within your monorepo setup. Thank you for bringing this to our attention!

**Comment by kiriyaga-txfusion** [comment]
Hello! I'm excited to share that we've just [released a new update](https://www.npmjs.com/package/@matterlabs/hardhat-zksync-deploy/v/1.2.0) that integrates the deployer directly into HRE. This enhancement promises to streamline our processes even further, making deployment tasks more efficient and seamless. Additionally, we've introduced several other functionalities designed to simplify your workflow. While our official documentation for these features is still undergoing review, you can find detailed descriptions in the plugin readme. Feel free to explore these new additions to enhance your experience!
