### ISSUE TITLE
Unexpected results when transferring ETH

### ISSUE THREAD

**Issue by bryanwee023** [matter-labs/hardhat-zksync#712]
#### 💥 Plugin name

`hardhat-zksync-node`

#### 📝 Description

Getting ETH balance for addresses is returning unexpected results.

#### 🔄 Reproduction Steps

1. Set up a zksync Hardhat project.
2. Add a minimal test into the `test/` folder.
    ```javascript
    describe("Transfer Ether", function() {
    
        let sender: zksync.Wallet;
        let receiver: zksync.Wallet;
    
        before(async function() {
            const provider = new Provider("http://127.0.0.1:8011");
    
            sender = new Wallet(RICH_WALLET_KEY, provider);
            receiver = new Wallet(POOR_WALLET_KEY, provider);
        });
    
        it("Should transfer ETH", async function() {
            // The first transfer is recorded
            console.log("\n==== FIRST TRANSFER ====");
            await sender.sendTransaction({
                to: receiver.getAddress(),
                value: ethers.parseEther("2")
            });
    
            console.log(`Sender's Funds: ${await sender.getBalance()}`);
            console.log(`Receiver's Funds: ${await receiver.getBalance()}`);
    
            // The second transfer is not recorded
            console.log("\n==== SECOND TRANSFER ====");
            await receiver.sendTransaction({
                to: sender.getAddress(),
                value: ethers.parseEther("1")
            });
    
            console.log(`Sender's Funds: ${await sender.getBalance()}`);
            console.log(`Receiver's Funds: ${await receiver.getBalance()}`);
        });
    });
    ```
3. Run the test with `npm run test`

#### 🤔 Expected Behavior

The receiver should have about 1 ETH after the second transfer.

#### 😯 Current Behavior

The receiver still has 2 ETH after the second transfer.

#### 🖥️ Environment

- **Node version**: Node 20.3.1
- **Operating System & Version**: macOS, 13.2, M1 Pro
- **Node dependencies**:
    ```
      "devDependencies": {
        "@matterlabs/hardhat-zksync-deploy": "^1.1.2",
        "@matterlabs/hardhat-zksync-node": "^1.0.1",
        "@matterlabs/hardhat-zksync-solc": "^1.0.6",
        "@matterlabs/zksync-contracts": "^0.6.1",
        "@types/chai": "^4.3.4",
        "@types/mocha": "^10.0.1",
        "chai": "^4.3.7",
        "ethers": "^6.9.2",
        "hardhat": "^2.12.4",
        "mocha": "^10.2.0",
        "ts-node": "^10.9.2",
        "typescript": "^4.9.5",
        "zksync-ethers": "^6.0.0"
      }
    ```
#### 📋 Additional Context

Removing the first pair of `getBalance` causes the second pair of `getBalance` to return the expected results. Maybe the get balance endpoint fails after repeated use?

#### 📎 Log Output

```
==== FIRST TRANSFER ====
Sender's Funds: 999999999997999843375750000000
Receiver's Funds: 2000000000000000000

==== SECOND TRANSFER ====
Sender's Funds: 999999999997999843375750000000
Receiver's Funds: 2000000000000000000
```

**Comment by bryanwee023** [comment]
Hey @nikola-bozin-txfusion ! I think that partially solves the problem, but I am still facing some inconsistencies.
```javascript
const provider = new Provider("http://127.0.0.1:8011");
const sender = new Wallet("0x7726827caac94a7f9e1b160f7ea819f172f7b6f9d2a97f992c38edeab82d4110", provider);
const receiver = new Wallet("0xfcba5e23977acf8e702e33c724ba40d68e020dd93cf26431297c50fee39d20a7", provider);

console.log(`Sender's Funds: ${await sender.getBalance()}`);
console.log(`Receiver's Funds: ${await receiver.getBalance()}`);

// The first transfer is not recorded
console.log("\n==== FIRST TRANSFER ====");
let tx = await sender1.sendTransaction({
    to: receiver.getAddress(),
    value: ethers.parseEther("2")
});

await tx.wait();
console.log(`Sender's Funds: ${await sender.getBalance()}`);
console.log(`Receiver's Funds: ${await receiver.getBalance()}`);
```

When I prepend the code with an initial `getBalance`, the results are wrong again.

**Comment by nikola-bozin-txfusion** [comment]
Hey, @bryanwee023 thanks for reporting the issue. 
This is not connected to `hardhat-zksync-node` plugin, but instead with era-test-node against which tests are ran.
We are working with a era-test-node team, to resolve this.

For now, you can use [Local Setup](https://docs.zksync.io/build/test-and-debug/dockerized-l1-l2-nodes.html) for your development to run tests.

**Comment by nzmpi** [comment]
Hey, @nikola-bozin-txfusion, sorry for bothering, but this problem is still not fixed. Any news?

**Comment by nikola-bozin-txfusion** [comment]
Hello, @nzmpi. The best thing to do is to follow this [issue](https://github.com/matter-labs/era-test-node/issues/217) for now.

**Comment by kiriyaga-txfusion** [comment]
There's a new workaround available for resolving this issue. Please check the related [problem-solving approach](https://github.com/matter-labs/era-test-node/issues/217#issuecomment-1981254689).
