### ISSUE TITLE
Path configuration is not supported

### ISSUE THREAD

**Issue by LuozhuZhang** [matter-labs/hardhat-zksync#74]
hardhat-zksync-solc is compiled according to ./contracts by default, and does not support path configuration

1. Please note that the folder is named "contracts", it cannot be "contract", otherwise zksync-solc cannot find the contract file

2. hardhat-zksync-solc also has a lot of incompatibilities with hardhat, which means there is a lot of work to be done, please let me know if you need help

<img width="600" alt="Screen Shot 2022-04-12 at 19 12 09" src="https://user-images.githubusercontent.com/70309026/162947749-22367064-3229-4ed4-b6dc-5a47e70bc863.png">

**Comment by ly0va** [comment]
Hi @hedgezhu thanks for the feedback!

The plugin works fine with non-default paths for me, could you please confirm you have the latest version, re-check and then send us some more info about your setup? A gist link to a minimal reproducible example will also be appreciated.

> hardhat-zksync-solc also has a lot of incompatibilities with hardhat

Please let us know what other features we're lacking. Feel free to submit a pull request as well.

**Comment by LuozhuZhang** [comment]
> could you please confirm you have the latest version, re-check and then send us some more info about your setup?

Here is my package.json, I think this is the latest version
```
    "@matterlabs/hardhat-zksync-deploy": "^0.1.5",
    "@matterlabs/hardhat-zksync-solc": "^0.3.0",
    "hardhat": "^2.9.3",
    "zksync-web3": "^0.4.0"
```

> Please let us know what other features we're lacking. Feel free to submit a pull request as well.

I'm looking the source code of hardhat-zksync-solc/depoloy, If I find something I can help, I'll submit a PR. Also I'm excited about zksync v2 and looking forward to reading your zkEVM source code
