### ISSUE TITLE
Use of `FactoryDeps` when tx reverts with "The code hash is not known"

### ISSUE THREAD

**Issue by clemsos** [matter-labs/hardhat-zksync#753]
#### 💥 Plugin name

hardhat-zksync-upgradable 

#### 📝 Description

When trying to deploy an upgradable contract, the tx reverts with a `"The code hash is not known"` error.

#### 🔄 Reproduction Steps

1. Step 1: get the implementation contract to deploy is [here](here https://github.com/unlock-protocol/unlock/blob/48526611b37108db49ddaa27b386a1e605320d5c/packages/contracts/src/contracts/Unlock/UnlockV13.sol)
2. Step 2: use the `hardhat-zksync-upgradable` lib to deploy a proxied version with the following params

```
  deployArgs: [ '<address of the deployer>' ],
  deployOptions: { initializer: 'initialize(address)' }
```
the actual function can be seen here

https://github.com/unlock-protocol/unlock/blob/f2941fc2cd21a85ddddc6c3a6579a146484a2e5c/packages/hardhat-helpers/src/zkSync.js#L30-L55

You can also clone the `zksync-support` of the [Unlock monorepo](https://github.com/unlock-protocol/unlock/pull/13078/files#diff-efdc83b02b38ece2b47c02aa4a0cd0072b6986a576aa1952290504ed180ce357), then 

1. `git clone https://github.com/unlock-protocol/unlock.git && git checkout zksync-support`
1. `yarn & yarn build` at root 
2. `cd governance`
3. `yarn hardhat deploy --unlock-version 13  --public-lock-version 14 --network zksyncSepolia` 

#### 🤔 Expected Behavior

Deploy the implementation, the proxyAdmin and a proxy contract correctly set

#### 😯 Current Behavior

 The proxyAdmin and implementation get deployed. The proxy deployment step fails

#### 📎 Log Output

```
yarn hardhat deploy --unlock-version 13  --public-lock-version 14 --network zksyncSepolia
Starting deployments on zkSync Era - Sepolia...
UNLOCK DEPLOYMENT > Deploying contracts on zkSync Era - Sepolia with the account: 0x246A13358Fb27523642D86367a51C2aEB137Ac6C
UNLOCK DEPLOYMENT > isLocalNet : false
Setting up version 13 from package
Implementation contract was deployed to 0xdab03e5E7f51065F4c41945a0718Bed21Ef9A9EF
Admin was deployed to 0xb52E38541e709622D86142DC2D50e2eE94017a06
An unexpected error occurred:

Error: execution reverted: "The code hash is not known" (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a54686520636f64652068617368206973206e6f74206b6e6f776e000000000000", reason="The code hash is not known", transaction={ "data": "0x9c4d535b00000000000000000000000000000000000000000000000000000000000000000100015f69aa55883cc3a9d732e813ef169a53ea385c3510e16035e8c10c3cac000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000dab03e5e7f51065f4c41945a0718bed21ef9a9ef000000000000000000000000b52e38541e709622d86142dc2d50e2ee94017a0600000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000024c4d66de8000000000000000000000000246a13358fb27523642d86367a51c2aeb137ac6c00000000000000000000000000000000000000000000000000000000", "from": "0x246A13358Fb27523642D86367a51C2aEB137Ac6C", "to": "0x0000000000000000000000000000000000008006" }, invocation=null, revert={ "args": [ "The code hash is not known" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.10.0)
    at makeError (/Users/clement/Dev/unlock/unlock/packages/hardhat-helpers/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at getBuiltinCallException (/Users/clement/Dev/unlock/unlock/packages/hardhat-helpers/node_modules/ethers/src.ts/abi/abi-coder.ts:118:21)
    at Function.getBuiltinCallException (/Users/clement/Dev/unlock/unlock/packages/hardhat-helpers/node_modules/ethers/src.ts/abi/abi-coder.ts:235:16)
    at Provider.getRpcError (/Users/clement/Dev/unlock/unlock/packages/hardhat-helpers/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:979:32)
    at /Users/clement/Dev/unlock/unlock/packages/hardhat-helpers/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'CALL_EXCEPTION',
  action: 'estimateGas',
  data: '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a54686520636f64652068617368206973206e6f74206b6e6f776e000000000000',
  reason: 'The code hash is not known',
  transaction: {
    to: '0x0000000000000000000000000000000000008006',
    data: '0x9c4d535b00000000000000000000000000000000000000000000000000000000000000000100015f69aa55883cc3a9d732e813ef169a53ea385c3510e16035e8c10c3cac000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000dab03e5e7f51065f4c41945a0718bed21ef9a9ef000000000000000000000000b52e38541e709622d86142dc2d50e2ee94017a0600000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000024c4d66de8000000000000000000000000246a13358fb27523642d86367a51c2aeb137ac6c00000000000000000000000000000000000000000000000000000000',
    from: '0x246A13358Fb27523642D86367a51C2aEB137Ac6C'
  },
  invocation: null,
  revert: {
    signature: 'Error(string)',
    name: 'Error',
    args: [ 'The code hash is not known' ]
  },
  shortMessage: 'execution reverted: "The code hash is not known"',
  info: {
    error: {
      code: 3,
      message: 'execution reverted: The code hash is not known',
      data: '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a54686520636f64652068617368206973206e6f74206b6e6f776e000000000000'
    },
    payload: {
      method: 'eth_estimateGas',
      params: [Array],
      id: 56,
      jsonrpc: '2.0'
    }
  }
}
```

**Comment by clemsos** [comment]
Reading the docs and similar issue #304, it seems the reverts happen because of a missing / wrong settings of the `factory_deps`. In the present case, logging the built artifact gives 

```
factoryDeps: {
      '0x010000edb51a9d1ee481114084d43cbe383212a0d19794ad33e80c87ce4b21a7': 'contracts/past-versions/UnlockV13.sol:ProxyAdmin',
      '0x0100015f00035b6caba21865ee421a517a22cba3044e486bdf2c0724d01375f7': 'contracts/past-versions/UnlockV13.sol:TransparentUpgradeableProxy'
    }
```

Not sure what I am doing wrong here ?

**Comment by kiriyaga-txfusion** [comment]
Hello @clemsos :wave: Usually, Hardhat plugins related to proxies and upgradable contracts are responsible for deploying proxies and admins for you, meaning that you don't need to deploy them from your code like you are doing here (check the log, you can see this: Admin was deployed to 0xb52E38541e709622D86142DC2D50e2eE94017a06).
But nonetheless, we should add support for deploying contracts from the implementation (not only ProxyAdmin in your case). Thus, we released a [new version of the plugin](https://www.npmjs.com/package/@matterlabs/hardhat-zksync-upgradable/v/1.2.4), so you can try with it.

P.S. If you got an error like this TypeError: Cannot destructure property 'hash' of '(intermediate value)' as it is null. in [line](https://github.com/unlock-protocol/unlock/blob/f2941fc2cd21a85ddddc6c3a6579a146484a2e5c/packages/hardhat-helpers/src/zkSync.js#L48), you can try with another extension on the contract like this:
`const { hash } = contract.deployTransaction;`

**Comment by clemsos** [comment]
@kiriyaga-txfusion thank you very much. I just tested with the new version and it worked just fine :)

Note that the `Admin was deployed to 0xb52E38541e709622D86142DC2D50e2eE94017a06` is added by the `deployProxy` of zksync upgradable plugin itself. 

Also thank you for the `hash` fix. It all works ~
