### ISSUE TITLE
zksolc 1.4.0 is not supported

### ISSUE THREAD

**Issue by boyuanx** [matter-labs/hardhat-zksync#811]
#### 💥 Plugin name

@matterlabs/hardhat-zksync-solc

#### 📝 Description

When attempting to compile with `zksolc` 1.4.0 and `@matterlabs/hardhat-zksync-solc` 1.1.3, the following error message is displayed:

`Error in plugin @matterlabs/hardhat-zksync-solc: The zksolc compiler version (1.4.0) in the hardhat config file is not within the allowed range. Please use versions 1.3.13 to 1.3.23.`

#### 🔄 Reproduction Steps

1. Use Solidity 0.8.24, `zksolc` 1.4.0, and `"@matterlabs/hardhat-zksync-solc": "1.1.3"`
2. Attempt to compile using `zksolc`
3. Error

#### 🤔 Expected Behavior

The contract should compile successfully.

#### 😯 Current Behavior

`@matterlabs/hardhat-zksync-solc` 1.1.3 doesn't seem to support the latest version of `zksolc`

#### 🖥️ Environment

- **Node version**: 20.9.0
- **Operating System & Version**: macOS 14.2.1 (23C71)
- **Other relevant environment details**:

#### 📋 Additional Context

For some reason, the exact same config works on my colleague's system. 

When using `latest` as the `zksolc` version, 1.3.23 is used.

I have attempted to delete `node_modules` and any cache folders.

#### 📎 Log Output

```
npx hardhat deploy --tags xxxx --network zkSyncTestnet
[
  {
    version: '0.8.24',
    settings: {
      optimizer: [Object],
      evmVersion: 'paris',
      outputSelection: [Object]
    }
  }
]
Error in plugin @matterlabs/hardhat-zksync-solc: The zksolc compiler version (1.4.0) in the hardhat config file is not within the allowed range. Please use versions 1.3.13 to 1.3.23.

For more info run Hardhat with --show-stack-traces
```

**Comment by mpopovac-txfusion** [comment]
Hey @boyuanx 👋, the hardhat-zksync-solc plugin has a caching mechanism for the list of allowed compiler versions to avoid throttling. It seems that the file responsible for the caching mechanism was updated in the past 24 hours, but during that time, there was no zksolc 1.4.0 compiler release (which you set explicitly in the hardhat config file). Please feel free to delete the file named `compilerVersionInfo.json` from your file system - this will trigger its update. The location of this file is the same as where the zksolc compilers are stored on your file system. For example, on a Mac, this path looks something like this: `/Users/<USERNAME>/Library/Caches/hardhat-nodejs/compilers-v2/zksolc`.

**Comment by boyuanx** [comment]
That worked, thank you :)
