### ISSUE TITLE
zksolc 1.4.0 is not supported by hardhat-zksync-verify

### ISSUE THREAD

**Issue by boyuanx** [matter-labs/hardhat-zksync#820]
#### 💥 Plugin name

"@matterlabs/hardhat-zksync-verify": "1.3.0"

#### 📝 Description

Contract compiled and deployed with zksolc 1.4.0 cannot be verified

#### 🔄 Reproduction Steps

1. Compile and deploy any contract with zksolc 1.4.0
2. Try to verify
3. Error

#### 🤔 Expected Behavior

The contract should be verified.

#### 😯 Current Behavior

The contract cannot be verified.

#### 🖥️ Environment

- **Node version**: 20.9.0
- **Operating System & Version**: macOS 14.2.1
- **Other relevant environment details**: None

#### 📋 Additional Context

None

#### 📎 Log Output

```
Successfully compiled 54 Solidity files
Your verification ID is: 3858
Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Unknown zksolc version: v1.4.0
```

**Comment by nikola-bozin-txfusion** [comment]
Hey @boyuanx, currently, our backend verification does not support the latest zksolc compiler version, 1.4.0. We will inform you when its added.

**Comment by nikola-bozin-txfusion** [comment]
@boyuanx version 1.4.0 is now supported for verifying smart contracts.

**Comment by Keref** [comment]
I have the same issue with latest hello-zksync.
yarn.lock shows `"@matterlabs/hardhat-zksync-verify@^1.4.2": version "1.4.2"`

But deploying gets me `Error in plugin @matterlabs/hardhat-zksync-verify: Backend verification error: Unknown zksolc version: v1.4.0`
