### ISSUE TITLE
Support deploymentType in Deployer (createAA, ...)

### ISSUE THREAD

**Issue by gergold** [matter-labs/hardhat-zksync#84]
It would be good to add a `deploymentType` optional parameter in the `Deployer` object constructor

https://github.com/matter-labs/hardhat-zksync/blob/a4441d3ce76033226d20cc8fd8d8ffe8bf63c1c4/packages/hardhat-zksync-deploy/src/deployer.ts#L21

... and then to use it when creating new instances of `zk.ContractFactory`

https://github.com/matter-labs/hardhat-zksync/blob/a4441d3ce76033226d20cc8fd8d8ffe8bf63c1c4/packages/hardhat-zksync-deploy/src/deployer.ts#L77

https://github.com/matter-labs/hardhat-zksync/blob/a4441d3ce76033226d20cc8fd8d8ffe8bf63c1c4/packages/hardhat-zksync-deploy/src/deployer.ts#L116

**Comment by mpavlovic-txfusion** [comment]
Hi @gergold! Thx for the suggestion I opened a PR to support this.

**Comment by githubdoramon** [comment]
> Hi @gergold! Thx for the suggestion I opened a PR to support this.

@mpavlovic-txfusion we should update docs with this change as well right?

**Comment by mpavlovic-txfusion** [comment]
> > Hi @gergold! Thx for the suggestion I opened a PR to support this.
> 
> @mpavlovic-txfusion we should update docs with this change as well right?

@githubdoramon It's a backward compatible change, since deployment type is added as an optional param, like suggested, and it will default to deploying contracts ('create') if not provided, but it will be good to mention in the docs that deploying custom accounts ('createAccount') is also possible with this.
