### ISSUE TITLE
The deploy-zksync script deploys contracts and treats all proxies as a single unique address within the deployment script.

### ISSUE THREAD

**Issue by wshino** [matter-labs/hardhat-zksync#846]
### 🐛 Bug Report for hardaht-zksync plugins

I'm currently facing an issue where the owner address in the deployed contract is not as the deployer. Last week, I successfully deployed contracts using a script without encountering any errors. You can see the output here: https://gist.github.com/wshino/2ad76f38d87af5b9655d0b0b931b4578

However, I've encountered some errors today related to the transferOwnership function, specifically the error message: `caller is not an owner`. There are no changes in contracts and scripts.
For reference, see the deployment script at: https://github.com/zkemail/email-wallet/blob/19f53ee9cae617ef4ea2c4d5dd866db8e4a36633/packages/contracts/deploy/deploy.ts#L138 
and the error log here: https://gist.github.com/wshino/99cadd894485a53de63d8c0ad5609737

Upon reviewing the deployment log again in light of this issue, I noticed an anomaly: all the ERC1967Proxy addresses are identical, which was not the case last week. You can compare the logs from last week and today at the following links:

Last week: https://gist.github.com/wshino/2ad76f38d87af5b9655d0b0b931b4578
Today: https://gist.github.com/wshino/99cadd894485a53de63d8c0ad5609737

I'm not sure what has changed, but this discrepancy has occurred. 
The repository I'm working is here: https://github.com/zkemail/email-wallet/pull/67. 
Currently, I'm modifying the proxy because it's malfunctioning due to the aforementioned issue. 
For more details, you can refer to the commit up to this hash: 
https://github.com/zkemail/email-wallet/commit/4822c45dadbe865107b6128a4c16cfc58ccb120e

Thank you.

#### 💥 Plugin name

    "@matterlabs/hardhat-zksync-deploy": "^1.1.2",

#### 📝 Description

Provide a clear and concise description of the bug.

#### 🔄 Reproduction Steps

1. Run `npx hardhat deploy-zksync --script deploy.ts --network zkSyncSepoliaTestnet`
2. All Proxies are recognized with the same address, and transferOwnership at the end fails.
3. ...

#### 🤔 Expected Behavior

Describe what you expected to happen.

#### 😯 Current Behavior

Describe what actually happened.

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by mpopovac-txfusion** [comment]
Hey @wshino :wave: It seems that yarn installs a newer version of the mentioned plugin (`1.2.0`) even if you specified `1.1.2` in the `package.json`. This newer version introduces caching mechanisms for contracts with the same name and the same bytecode. If you want to force the deployment of the same contracts several times, you need to set the `forceDeploy` field to true in the network config like this:

```
networks: {
    zkSyncSepoliaTestnet: {
      url: "https://sepolia.era.zksync.dev/",
      ethNetwork: "sepolia",
      zksync: true,
      verifyURL: "https://explorer.sepolia.era.zksync.dev/contract_verification",
      forceDeploy: true
    },
    ...
}
```

In the next patch version, we will set force deployment to `true` by default.

**Comment by wshino** [comment]
Thank you for your reply @mpopovac-txfusion. I totally understood. I was using 1.2.0. 
I set `forceDeploy: true` and then deploy them again, it works correctly. Thank you again your help.
