### ISSUE TITLE
The "glob" update from 7.x.x to 8.x.x broke the deployer on Windows

### ISSUE THREAD

**Issue by Laurianti** [matter-labs/hardhat-zksync#85]
Glob 8 has a breaking change on Windows about the path:

https://github.com/isaacs/node-glob/commit/af4207ba7325203b12b9009d6c0b18ed34f49f20

Now the deployer cannot find any ts/js files on Windows:

https://github.com/matter-labs/hardhat-zksync/blob/82a5303a16b1a478b49f01052e1c6449e52b08fa/packages/hardhat-zksync-deploy/src/plugin.ts#L18

files[] is empty

**Comment by ly0va** [comment]
Thanks for reporting @Laurianti 
Will have a look

**Comment by ly0va** [comment]
Will be fixed in the next release
