### ISSUE TITLE
A version problem occurred during compilation

### ISSUE THREAD

**Issue by showlocked** [matter-labs/hardhat-zksync#868]
The following error occurs when I compile with an older version:
Error in plugin @matterlabs/hardhat-zksync-solc: The zksolc compiler version (1.3.5) in the hardhat config file is not within the allowed range. Please use versions 1.3.13 to 1.4.0.
When I look at the source code, I find that the minimum version number is restricted. Why do I do this? How do I compile the old version of the contract when I do contract verification? How do I compile its bytecode？

**Comment by showlocked** [comment]
But what I want to do is build locally to provide a contract validation service for others to use

**Comment by mpopovac-txfusion** [comment]
You can manually override min version in the allowed range of zksolc compilers by finding `compilerVersionInfo.json` that is placed in the same directory as cached zksolc compilers. Here is the example of the path on Mac OS: `/Users/<USERNAME>/Library/Caches/hardhat-nodejs/compilers-v2/zksolc/compilerVersionInfo.json`

**Comment by showlocked** [comment]
thanks, it resolved my problem, and another way is to directly modify download.js which is what I did earlier, but it does look a little bad
