### ISSUE TITLE
nft eth

### ISSUE THREAD

**Issue by skippyy-96** [matter-labs/hardhat-zksync#950]
#### 💥 Plugin name

Provide a plugin name where the bug appeared.

#### 📝 Description

Provide a clear and concise description of the bug.

#### 🔄 Reproduction Steps

1. Step 1
2. Step 2
3. ...

#### 🤔 Expected Behavior

Describe what you expected to happen.

#### 😯 Current Behavior

Describe what actually happened.

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by kiriyaga-txfusion** [comment]
We will close the issue due to insufficient information.
