### ISSUE TITLE
LLVM IR generator definition pass error

### ISSUE THREAD

**Issue by mikhailxyz** [matter-labs/hardhat-zksync#99]
I'm trying to compile Safe contracts for zksync, but I'm facing an error:

> Error in plugin @matterlabs/hardhat-zksync-solc: The contract `contracts/proxies/GnosisSafeProxyFactory.sol:GnosisSafeProxyFactory` LLVM IR generator definition pass error: Contract with identifier `GnosisSafeProxy_39.GnosisSafeProxy_39_deployed` not found in the project

I've tried it with Solidity 0.7.6 and 0.8.15, same error in both cases

To reproduce, you can use https://github.com/safe-global/safe-contracts/tree/zksync:
1. Clone the repo
2. run `yarn`

I'm using macOS 12.5 with an M1 laptop. Would appreciate your help in debugging

**Comment by ly0va** [comment]
Thanks for the feedback @mikhailxyz!
We'll take a look at it shortly.

cc @AntonD3 @hedgar2017

**Comment by hedgar2017** [comment]
The problem is type(*).runtimeCode. We do not support it.
I can improve the error message though.

**Comment by ultraviolet10** [comment]
Is there a specified solution to this issue? 
The problem seems to be arising from imports?

**Comment by 1500256797** [comment]
what should we do ? how to solve this bug ?

**Comment by hedgar2017** [comment]
> what should we do ? how to solve this bug ?

It is not a bug, but a feature  unsupported on our architecture.
The only way is to remove runtimeCode access from the dependency.

**Comment by Senya123** [comment]
Any solutions guys?

**Comment by hedgar2017** [comment]
> Can't run any test in every directory
> 
> 

Could you elaborate?

**Comment by Senya123** [comment]
> > Can't run any test in every directory
> 
> Could you elaborate?

https://github.com/matter-labs/hardhat-zksync/issues/1040

**Comment by Senya123** [comment]
> > Can't run any test in every directory
> 
> Could you elaborate?

Since i download the foundry-zksync i can't run any test in every directory via forge test. I receive the issue above 👆  Any thoughts? I have found the guy who has the same issue and he couldn't resolve it also. He 
<img width="726" alt="Screenshot 2024-05-05 at 10 16 41" src="https://github.com/matter-labs/hardhat-zksync/assets/26926656/5a5192e8-1437-4fd5-89a2-5f10280b6e47">

**Comment by Senya123** [comment]
> > Can't run any test in every directory
> 
> Could you elaborate?

How to get rid of it ? 😁
